// Actual loopback collector -> node_exporter -> Prometheus -> Alertmanager -> local receiver.
// Synthetic encrypted objects exercise monitoring only; they do not prove PG backup recovery or RPO.
import assert from 'node:assert/strict';
import { spawn, execFileSync } from 'node:child_process';
import { createHash, randomBytes } from 'node:crypto';
import { createServer } from 'node:http';
import { createServer as tlsServer } from 'node:tls';
import { createServer as portServer } from 'node:net';
import { chmod, mkdir, readFile, rm, stat, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { setTimeout as delay } from 'node:timers/promises';
import { collectMetrics, publishMetrics } from '../../infra/ops/collect-metrics.mjs';

const root = resolve(import.meta.dirname, '../..');
const stamp = new Date().toISOString().replaceAll(':', '-').replaceAll('.', '-');
const directory = resolve(root, '.local', `monitoring-chain-${randomBytes(6).toString('hex')}`);
const evidence = resolve(root, 'docs/evidence/T22/monitoring-chain');
const report = { started: new Date().toISOString(), scope: 'Real loopback monitoring transport, exact production alert hold and recovery; synthetic encrypted file fixtures, not production delivery, backups or RPO.', phases: [], tools: {}, exitCode: 1 };
const children = []; const servers = []; const notifications = [];
const digest = (bytes) => createHash('sha256').update(bytes).digest('hex');
async function port() { const server = portServer(); await new Promise((done) => server.listen(0, '127.0.0.1', done)); const value = server.address().port; await new Promise((done) => server.close(done)); return value; }
function start(binary, args) { const child = spawn(binary, args, { cwd: directory, shell: false, stdio: ['ignore', 'pipe', 'pipe'] }); let log = ''; child.stdout.on('data', (bytes) => { log += bytes; }); child.stderr.on('data', (bytes) => { log += bytes; }); const completion = new Promise((done) => { child.once('error', () => done(127)); child.once('close', (code) => done(code)); }); const handle = { child, completion, log: () => log }; children.push(handle); return handle; }
async function waitFor(action, label, deadline = 20_000) { const until = Date.now() + deadline; while (Date.now() < until) { if (children.some(({ child }) => child.exitCode !== null)) throw new Error('A required monitoring process exited.'); try { if (await action()) return; } catch { /* bounded readiness observation */ } await delay(250); } throw new Error(`${label} deadline exceeded.`); }
async function json(url) { const response = await fetch(url, { signal: AbortSignal.timeout(3000) }); assert.equal(response.status, 200); return response.json(); }
try {
  await mkdir(directory, { recursive: true, mode: 0o700 }); await mkdir(evidence, { recursive: true });
  const binaries = { prometheus: ['3.15.0', 'prometheus-3.15.0.linux-amd64/prometheus'], alertmanager: ['0.34.1', 'alertmanager-0.34.1.linux-amd64/alertmanager'], exporter: ['1.12.1', 'node_exporter-1.12.1.linux-amd64/node_exporter'] };
  for (const [name, [version, path]] of Object.entries(binaries)) { const binary = resolve(root, '.local/security-tools', path); assert.ok(execFileSync(binary, ['--version'], { encoding: 'utf8' }).includes(`version ${version}`)); report.tools[name] = { version, binarySha256: digest(await readFile(binary)) }; binaries[name] = binary; }
  const paths = ['infra/ops/collect-metrics.mjs', 'infra/ops/archive-wal.sh', 'infra/ops/identity-alerts.yaml', 'infra/ops/prometheus.yaml', 'infra/ops/systemd/identity-ops-metrics.service', 'infra/ops/systemd/identity-ops-metrics.timer', 'tests/ops/monitoring-chain.mjs']; report.sourceSha256 = {}; for (const path of paths) report.sourceSha256[path] = digest(await readFile(resolve(root, path)));
  const base = resolve(directory, 'base'); const wal = resolve(directory, 'wal'); const textfiles = resolve(directory, 'textfiles'); await mkdir(base, { mode: 0o700 }); await mkdir(wal, { mode: 0o700 }); await mkdir(textfiles, { mode: 0o700 });
  const age = process.env.AGE_BINARY ?? resolve(root, '.local/security-tools/age/age'); const keygen = process.env.AGE_KEYGEN_BINARY ?? resolve(root, '.local/security-tools/age/age-keygen'); const identity = resolve(directory, 'age.key'); execFileSync(keygen, ['-o', identity], { stdio: ['ignore', 'ignore', 'pipe'] }); const recipient = execFileSync(keygen, ['-y', identity], { encoding: 'utf8' }).trim(); const plain = resolve(directory, 'synthetic-input'); await writeFile(plain, 'Synthetic monitoring payload; not a PostgreSQL backup.\n', { mode: 0o600 });
  const name = '20261009T010000Z-1.tar.age'; execFileSync(age, ['-r', recipient, '-o', resolve(base, name), plain]); await chmod(resolve(base, name), 0o600); const encrypted = await readFile(resolve(base, name)); await writeFile(resolve(base, `${name}.sha256`), `${digest(encrypted)}  ${name}\n`, { mode: 0o600 }); await writeFile(resolve(base, 'last-success.json'), JSON.stringify({ version: 1, completed_at: Math.floor(Date.now() / 1000), backup_name: name, ciphertext_bytes: encrypted.length, ciphertext_sha256: digest(encrypted) }), { mode: 0o600 });
  const device = (await stat(directory, { bigint: true })).dev;
  execFileSync('sh', [resolve(root, 'infra/ops/archive-wal.sh'), plain, '000000010000000000000001'], { env: { ...process.env, WAL_ARCHIVE_DIRECTORY: wal, WAL_ARCHIVE_DEVICE: String(device), AGE_BINARY: age, AGE_RECIPIENT: recipient }, stdio: ['ignore', 'ignore', 'pipe'] }); const walReceipt = await readFile(resolve(wal, 'last-success.json'));
  const key = resolve(directory, 'tls.key'); const certificate = resolve(directory, 'tls.pem'); execFileSync('openssl', ['req', '-x509', '-newkey', 'rsa:2048', '-nodes', '-days', '30', '-subj', '/CN=localhost', '-addext', 'subjectAltName=DNS:localhost', '-keyout', key, '-out', certificate], { stdio: ['ignore', 'ignore', 'pipe'] });
  const tls = tlsServer({ key: await readFile(key), cert: await readFile(certificate) }, (socket) => socket.end()); tls.on('tlsClientError', () => {}); await new Promise((done) => tls.listen(0, '127.0.0.1', done)); servers.push(tls);
  const config = { dataDirectory: directory, dataDevice: device, backupDirectory: base, backupDevice: device, walDirectory: wal, walDevice: device, issuer: new URL(`https://localhost:${tls.address().port}`), caFile: certificate, output: resolve(textfiles, 'identity-ops.prom') };
  const receiver = createServer(async (request, response) => { try { assert.equal(request.method, 'POST'); assert.equal(request.url, '/local-alert'); let bytes = ''; for await (const part of request) { bytes += part; assert.ok(bytes.length <= 100_000); } const body = JSON.parse(bytes); for (const alert of body.alerts ?? []) if (alert.labels?.alertname === 'IdentityOpsCheckFailed' && alert.labels?.check === 'wal_archive') notifications.push({ status: alert.status, received: Date.now(), alertname: alert.labels.alertname, check: alert.labels.check }); response.writeHead(200); response.end('{}'); } catch { response.writeHead(400); response.end(); } }); await new Promise((done) => receiver.listen(0, '127.0.0.1', done)); servers.push(receiver);
  const exporterPort = await port(); const prometheusPort = await port(); const alertmanagerPort = await port();
  const alertmanagerConfig = resolve(directory, 'alertmanager.yaml'); await writeFile(alertmanagerConfig, `route:\n  receiver: ignore\n  group_by: [alertname, check]\n  group_wait: 0s\n  group_interval: 1s\n  repeat_interval: 1h\n  routes:\n    - receiver: local-verification\n      matchers: ['alertname="IdentityOpsCheckFailed"', 'check="wal_archive"']\nreceivers:\n  - name: ignore\n  - name: local-verification\n    webhook_configs:\n      - url: http://127.0.0.1:${receiver.address().port}/local-alert\n        send_resolved: true\n`, { mode: 0o600 });
  const production = await readFile(resolve(root, 'infra/ops/prometheus.yaml'), 'utf8'); assert.ok(production.includes('job_name: identity-ops')); const prometheusConfig = resolve(directory, 'prometheus.yaml'); await writeFile(prometheusConfig, production.replaceAll('15s', '1s').replace('/etc/prometheus/identity-alerts.yaml', resolve(root, 'infra/ops/identity-alerts.yaml')).replace('identity-ops-exporter:9100', `127.0.0.1:${exporterPort}`).replace('identity-alertmanager:9093', `127.0.0.1:${alertmanagerPort}`).replaceAll('/run/secrets/metrics-token', resolve(directory, 'metrics-token')), { mode: 0o600 }); await writeFile(resolve(directory, 'metrics-token'), randomBytes(32).toString('hex'), { mode: 0o600 });
  execFileSync(resolve(root, '.local/security-tools/prometheus-3.15.0.linux-amd64/promtool'), ['check', 'config', prometheusConfig], { stdio: ['ignore', 'ignore', 'pipe'] }); execFileSync(resolve(root, '.local/security-tools/alertmanager-0.34.1.linux-amd64/amtool'), ['check-config', alertmanagerConfig], { stdio: ['ignore', 'ignore', 'pipe'] });
  const healthy = await collectMetrics(config); assert.equal(healthy.success, true); await publishMetrics(config.output, healthy.text);
  start(binaries.exporter, ['--web.listen-address', `127.0.0.1:${exporterPort}`, '--collector.disable-defaults', '--collector.textfile', '--collector.textfile.directory', textfiles]); start(binaries.alertmanager, ['--web.listen-address', `127.0.0.1:${alertmanagerPort}`, '--cluster.listen-address=', '--config.file', alertmanagerConfig, '--storage.path', resolve(directory, 'alertmanager-data')]); start(binaries.prometheus, ['--web.listen-address', `127.0.0.1:${prometheusPort}`, '--config.file', prometheusConfig, '--storage.tsdb.path', resolve(directory, 'prometheus-data')]);
  const origin = `http://127.0.0.1:${prometheusPort}`; const query = async (expression) => (await json(`${origin}/api/v1/query?query=${encodeURIComponent(expression)}`)).data.result;
  await waitFor(async () => (await query('identity_ops_collection_success{job="identity-ops",check="wal_archive"}')).some((sample) => sample.value[1] === '1'), 'Real healthy scrape'); assert.equal(notifications.length, 0); report.phases.push({ name: 'healthy collector and actual exporter scrape', exitCode: 0 });
  await rm(resolve(wal, 'last-success.json')); const failedAt = Date.now(); const failure = await collectMetrics(config); assert.equal(failure.success, false); assert.equal(failure.checks.wal_archive, 0); await publishMetrics(config.output, failure.text);
  await waitFor(async () => (await query('ALERTS{alertname="IdentityOpsCheckFailed",check="wal_archive",alertstate="pending"}')).length === 1, 'Pending alert before exact one-minute hold'); assert.equal(notifications.length, 0); report.phases.push({ name: 'missing receipt publishes failure and pending rule', exitCode: 0 });
  await waitFor(async () => notifications.some((notice) => notice.status === 'firing'), 'Actual local firing webhook', 100_000); const firing = notifications.find((notice) => notice.status === 'firing'); assert.ok(firing.received - failedAt >= 59_000, 'Production one-minute alert hold must not be shortened.'); assert.equal((await query('ALERTS{alertname="IdentityOpsCheckFailed",check="wal_archive",alertstate="firing"}')).length, 1); report.phases.push({ name: 'actual Prometheus firing through Alertmanager to loopback receiver', exitCode: 0, holdObservedMs: firing.received - failedAt });
  await writeFile(resolve(wal, 'last-success.json'), walReceipt, { mode: 0o600 }); const recovered = await collectMetrics(config); assert.equal(recovered.success, true); await publishMetrics(config.output, recovered.text); await waitFor(async () => notifications.some((notice) => notice.status === 'resolved') && (await query('ALERTS{alertname="IdentityOpsCheckFailed",check="wal_archive"}')).length === 0, 'Actual local recovery webhook', 40_000); report.phases.push({ name: 'verified recovery clears rule and delivers resolved webhook', exitCode: 0 });
  report.notifications = notifications.map(({ status, alertname, check }) => ({ status, alertname, check })); report.method = { transport: 'loopback only; exporter real textfile collector; production rules unchanged', sampling: 'laboratory scrape/evaluation interval 1s replaces production 15s; exact for:1m unchanged', fixture: 'actual statfs, trusted local TLS and actual age ciphertext/SHA receipts; plaintext is explicitly synthetic monitoring input', externallyDelivered: false };
  for (const path of paths) assert.equal(digest(await readFile(resolve(root, path))), report.sourceSha256[path], 'Monitored source changed during validation.'); report.exitCode = 0;
} catch { report.failure = 'Actual monitoring chain failed; bounded local diagnostics are retained privately. No credentials, paths or webhook bodies are published.'; }
finally {
  for (const handle of children) { if (handle.child.exitCode === null) handle.child.kill('SIGTERM'); await Promise.race([handle.completion, delay(5000).then(() => handle.child.kill('SIGKILL'))]); }
  for (const server of servers) await new Promise((done) => server.close(done)); await mkdir(evidence, { recursive: true }); report.completed = new Date().toISOString(); await writeFile(resolve(evidence, `${stamp}${report.exitCode ? '-failure' : ''}.json`), JSON.stringify(report, null, 2) + '\n');
  if (report.exitCode) { await mkdir(resolve(directory, 'diagnostics'), { recursive: true, mode: 0o700 }); for (const [index, child] of children.entries()) await writeFile(resolve(directory, 'diagnostics', `${index}.txt`), child.log(), { mode: 0o600 }); } else await rm(directory, { recursive: true, force: true }); console.log(`Actual local monitoring chain exit ${report.exitCode}.`); process.exitCode = report.exitCode;
}
