// Five-service local-review deploy/rollback exercise. Own containers/CA/secrets only.
import assert from 'node:assert/strict';
import { randomBytes } from 'node:crypto';
import { chown, chmod, mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import { createServer } from 'node:net';
import { resolve } from 'node:path';
import { configuration, databaseFacts, executeCommand, runRelease } from '../../infra/ops/release.mjs';
import { compose, docker, fixture as loadFixture, hash, privatePhrase, root, run, services } from './release-stack-helper.mjs';

const pgImage='docker.m.daocloud.io/library/postgres:17.11-bookworm@sha256:3645570cccdfa447589da9f57dd740faa29b30938e861289a5574b6ca6b03826';
const redisImage='docker.m.daocloud.io/library/redis:7.4@sha256:4fa24486b8bcca8eec45ee0eb166edc674795e53a2b53d1a9ef263eecebaac85';
const mailImage='docker.m.daocloud.io/axllent/mailpit:v1.31.4@sha256:b68349e3a014b90c5610bfb26b2ae36f3892d7b8cf25ee140c6c71c98d2fcf48';
const directory=resolve(root,'.local/release-stack-'+randomBytes(8).toString('hex'));const project='release-stack-'+randomBytes(6).toString('hex');
const oldRuntime='auth-rust-runtime:t23-2c9c712',newRuntime='auth-rust-runtime:t23-df28706',edge='auth-rust-edge:t23-df28706';
const report={started:new Date().toISOString(),scope:'Five real services with local CA TLS/test SMTP; local-review only, not production DNS/SMTP/HA',phases:[],exitCode:1};
let data;let nickname;const nss=resolve('/root','.pki/nssdb');
const sourceFiles=['infra/ops/release.mjs','infra/Caddyfile.prod','infra/ops/base-backup.sh','Cargo.lock','package-lock.json','tests/ops/release-stack.mjs','tests/ops/release-stack-helper.mjs','tests/ops/release-stack-bootstrap.mjs','tests/ops/release-stack-smoke.mjs'];
async function freePort(){const server=createServer();await new Promise((done)=>server.listen(0,'127.0.0.1',done));const port=server.address().port;await new Promise((done)=>server.close(done));return port;}
async function save(name,value,mode=0o600){const path=resolve(directory,name);await writeFile(path,value,{mode});return path;}
function eventExecutor(program,args,options){return executeCommand(program,args,{...options,env:{...process.env,...options.env,RELEASE_STACK_DIRECTORY:directory}});}
async function facts(){return databaseFacts({project,composeFile:resolve(directory,'compose.yaml'),envFile:resolve(directory,'release.env'),databaseUser:'postgres',databaseName:'identity_test',encryptionKeysFile:resolve(directory,'keys.json'),rustImage:newRuntime,edgeImage:edge});}
if(process.argv[2]==='--facts'){try{const data=loadFixture(process.env.RELEASE_STACK_DIRECTORY);console.log(JSON.stringify(await databaseFacts({project:data.project,composeFile:resolve(data.directory,'compose.yaml'),envFile:resolve(data.directory,'release.env'),databaseUser:'postgres',databaseName:'identity_test',encryptionKeysFile:resolve(data.directory,'keys.json'),rustImage:process.env.RUST_IMAGE,edgeImage:process.env.EDGE_IMAGE})));}catch{process.exitCode=1;}}
else {try{
 report.sourceBefore={};for(const file of sourceFiles)report.sourceBefore[file]=hash(await readFile(resolve(root,file)));report.sourceCommit=run('git',['-C',root,'rev-parse','HEAD']).trim();

 await mkdir(directory,{mode:0o700});await mkdir(resolve(directory,'secret'),{mode:0o755});await mkdir(resolve(directory,'state'),{mode:0o700});
 const port=await freePort();const mailPort=await freePort();data={directory,project,port,mailPort,issuer:'https://identity.release.test:'+port,appA:'https://app-a.release.test:'+port,appB:'https://app-b.release.test:'+port,password:privatePhrase(),adminEmail:'admin-stack@example.test'};await save('fixture.json',JSON.stringify(data));
 const revisions={};for(const name of[oldRuntime,newRuntime,edge]){const raw=JSON.parse(docker('image','inspect',name));revisions[name]={id:raw[0].Id,revision:raw[0].Config.Labels?.['org.opencontainers.image.revision']};}report.images=revisions;assert.equal(revisions[newRuntime].revision,'df28706a70118404ba60d3ca994863d271067f84');
 run('openssl',['req','-x509','-newkey','rsa:2048','-nodes','-days','2','-subj','/CN=Identity release local CA','-keyout',resolve(directory,'ca-key.pem'),'-out',resolve(directory,'ca.pem')]);
 run('openssl',['req','-new','-newkey','rsa:2048','-nodes','-subj','/CN=identity.release.test','-keyout',resolve(directory,'secret/tls-key.pem'),'-out',resolve(directory,'leaf.csr')]);await save('extensions.cnf','subjectAltName=DNS:identity.release.test,DNS:app-a.release.test,DNS:app-b.release.test\nbasicConstraints=CA:FALSE\nkeyUsage=digitalSignature,keyEncipherment\nextendedKeyUsage=serverAuth\n');run('openssl',['x509','-req','-in',resolve(directory,'leaf.csr'),'-CA',resolve(directory,'ca.pem'),'-CAkey',resolve(directory,'ca-key.pem'),'-CAcreateserial','-days','2','-extfile',resolve(directory,'extensions.cnf'),'-out',resolve(directory,'secret/tls.pem')]);
 run('openssl',['genpkey','-algorithm','RSA','-pkeyopt','rsa_keygen_bits:2048','-out',resolve(directory,'secret/signing.pem')]);await save('keys.json',JSON.stringify({stack:randomBytes(32).toString('base64')}));await save('smtp-password',randomBytes(24).toString('base64url'));await save('previous.json','{"keys":[]}');
 for(const name of['secret/signing.pem','secret/tls-key.pem','secret/tls.pem','keys.json','smtp-password','previous.json']){await chown(resolve(directory,name),10001,10001);await chmod(resolve(directory,name),0o600);}
 const bundle=(await readFile('/etc/ssl/certs/ca-certificates.crt','utf8'))+'\n'+await readFile(resolve(directory,'ca.pem'),'utf8');await save('ca-bundle.pem',bundle,0o644);
 await mkdir(nss,{recursive:true});try{run('certutil',['-L','-d','sql:'+nss]);}catch{run('certutil',['-N','--empty-password','-d','sql:'+nss]);}nickname='identity-release-'+randomBytes(6).toString('hex');run('certutil',['-A','-d','sql:'+nss,'-n',nickname,'-t','C,,','-i',resolve(directory,'ca.pem')]);
 const identityEnv='APP_ENV=test\nBIND=0.0.0.0:8080\nISSUER='+data.issuer+'\nRP_ID=identity.release.test\nDATABASE_URL=postgres://postgres@postgres/identity_test\nREDIS_URL=redis://redis:6379\nSIGNING_KEY_FILE=/run/secrets/signing.pem\nSIGNING_KID=stack-signing\nENCRYPTION_KEYS_FILE=/run/secrets/keys.json\nACTIVE_ENCRYPTION_KID=stack\nSMTP_HOST=mailpit\nSMTP_PORT=1025\nSMTP_FROM=no-reply@identity.release.test\nSMTP_TLS=disabled\n';await save('identity.env',identityEnv);
 for(const name of['a','b'])await save('demo-'+name+'.env','APP_ENV=test\nBIND=0.0.0.0:808'+(name==='a'?'2':'3')+'\nBFF_PUBLIC_ORIGIN='+data[name==='a'?'appA':'appB']+'\nISSUER='+data.issuer+'\nBFF_CLIENT_ID=stack-'+name+'\nBFF_CLIENT_SECRET_FILE=/run/secrets/client-secret\nDATABASE_URL=postgres://postgres@postgres/identity_test\nBFF_NAMESPACE=stack_'+name+'\nBFF_COOKIE_NAME=__Host-stack-'+name+'\nENCRYPTION_KEYS_FILE=/run/secrets/keys.json\nACTIVE_ENCRYPTION_KID=stack\nSSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt\n');
 for(const name of['a','b']){await save('secret/client-'+name,randomBytes(32).toString('base64url'));await chown(resolve(directory,'secret/client-'+name),10001,10001);}
 let caddy=await readFile(resolve(root,'infra/Caddyfile.prod'),'utf8');caddy=caddy.replace('https_port 8443','https_port '+port).replaceAll('{$IDENTITY_HOST}', 'identity.release.test:'+port).replaceAll('{$DEMO_A_HOST}','app-a.release.test:'+port).replaceAll('{$DEMO_B_HOST}','app-b.release.test:'+port).replaceAll(':8080,',':8080,');caddy=caddy.replace(/^(identity\.release\.test|app-[ab]\.release\.test):(\d+) \{/gmu,'$1:$2 {\n\ttls /run/secrets/tls.pem /run/secrets/tls-key.pem');caddy=caddy.replace(/http:\/\/[^\n]+\{[\s\S]*?\n\}/u,'');await save('Caddyfile',caddy,0o644);
 const volumes="['"+resolve(directory,'secret/signing.pem')+":/run/secrets/signing.pem:ro', '"+resolve(directory,'keys.json')+":/run/secrets/keys.json:ro', '"+resolve(directory,'smtp-password')+":/run/secrets/smtp-password:ro', '"+resolve(directory,'previous.json')+":/run/secrets/jwks-previous.json:ro', '"+resolve(directory,'ca-bundle.pem')+":/etc/ssl/certs/ca-certificates.crt:ro']";
 let yaml='name: '+project+'\nx-rust: &rust\n  image: ${RUST_IMAGE}\n  user: "10001:10001"\n  read_only: true\n  restart: unless-stopped\n  cap_drop: [ALL]\n  security_opt: [no-new-privileges:true]\n  tmpfs: ["/tmp:size=16m,mode=1777"]\n  networks: [private]\n  volumes: '+volumes+'\nservices:\n  postgres:\n    image: '+pgImage+'\n    environment: {POSTGRES_HOST_AUTH_METHOD: trust, POSTGRES_DB: identity_test}\n    networks: [private]\n    healthcheck: {test: [CMD, pg_isready, -U, postgres], interval: 1s, timeout: 2s, retries: 30}\n  redis:\n    image: '+redisImage+'\n    networks: [private]\n    healthcheck: {test: [CMD, redis-cli, ping], interval: 1s, timeout: 2s, retries: 30}\n  mailpit:\n    image: '+mailImage+'\n    networks: [private, ingress]\n    ports: ["127.0.0.1:'+mailPort+':8025"]\n    healthcheck: {test: [CMD, /mailpit, readyz], interval: 1s, timeout: 2s, retries: 30}\n';
 for(const[service,binary,bind,envfile]of[['api','identity-server',8080,'identity.env'],['worker','identity-worker',8081,'identity.env'],['demo-a-bff','demo-bff',8082,'demo-a.env'],['demo-b-bff','demo-bff',8083,'demo-b.env']]){yaml+='  '+service+':\n    <<: *rust\n    command: ['+binary+']\n    env_file: '+resolve(directory,envfile)+'\n    environment: {BIND: "0.0.0.0:'+bind+'"}\n';if(service.startsWith('demo-'))yaml+='    volumes: ["'+resolve(directory,'secret/client-'+(service==='demo-a-bff'?'a':'b'))+':/run/secrets/client-secret:ro", "'+resolve(directory,'keys.json')+':/run/secrets/keys.json:ro", "'+resolve(directory,'ca-bundle.pem')+':/etc/ssl/certs/ca-certificates.crt:ro"]\n';yaml+='    healthcheck: {test: [CMD, curl, --fail, --silent, http://127.0.0.1:'+bind+'/health/'+(service==='api'||service==='worker'?'ready':'live')+'], interval: 1s, timeout: 2s, retries: 30}\n';}
 yaml+='  edge:\n    image: ${EDGE_IMAGE}\n    user: "10001:10001"\n    read_only: true\n    cap_drop: [ALL]\n    security_opt: [no-new-privileges:true]\n    environment: {TLS_EMAIL: operations@example}\n    networks:\n      private:\n        aliases: [identity.release.test, app-a.release.test, app-b.release.test]\n      ingress: {}\n    ports: ["127.0.0.1:'+port+':'+port+'"]\n    volumes: ["'+resolve(directory,'Caddyfile')+':/etc/caddy/Caddyfile:ro", "'+resolve(directory,'secret/tls.pem')+':/run/secrets/tls.pem:ro", "'+resolve(directory,'secret/tls-key.pem')+':/run/secrets/tls-key.pem:ro"]\n    tmpfs: ["/tmp:size=16m,mode=1777", "/data:size=16m,mode=1777", "/config:size=16m,mode=1777"]\n  migrate:\n    <<: *rust\n    profiles: [maintenance]\n    env_file: '+resolve(directory,'identity.env')+'\n    command: [identity-migrate, --test-target]\nnetworks:\n  private: {internal: true}\n  ingress: {}\n';await save('compose.yaml',yaml);await save('release.env','RUST_IMAGE='+oldRuntime+'\nEDGE_IMAGE='+edge+'\n');
 docker(...compose(data,['up','-d','--wait','postgres','redis','mailpit']));docker(...compose(data,['run','--rm','--no-deps','migrate']));
 const bootstrap=await executeCommand('docker',compose(data,['run','--rm','--no-deps','-T','api','identity-admin-cli','bootstrap','--email',data.adminEmail]),{input:data.password+'\n'});assert.equal(bootstrap.code,0);
 // The first app-only start allows the genuine administrator to bind a factor/create clients.
 docker(...compose(data,['up','-d','--no-deps','api','worker','edge']));docker(...compose(data,['up','-d','--no-deps','--wait','api','worker']));
 let ready=false;for(let attempt=0;attempt<100;attempt++){try{const result=await import('./release-stack-helper.mjs').then((module)=>module.request(data,data.issuer,'/health/ready'));report.initialTlsStatus=result.status;if(result.status===200){ready=true;break;}}catch(error){report.initialTlsError=error.message;ready=false;if(attempt===99){report.ownedPorts=docker(...compose(data,['port','edge',String(port)])).trim();report.renderedEdge=JSON.parse(docker(...compose(data,['config','--format','json']))).services.edge.ports;}}await new Promise((done)=>setTimeout(done,100));}assert.ok(ready,'Actual local edge/API TLS readiness failed.');
 await import('./release-stack-bootstrap.mjs').then((module)=>module.bootstrap(directory));
 const pg=docker(...compose(data,['ps','-q','postgres'])).trim();const age=process.env.AGE_BINARY??resolve(root,'.local/security-tools/age/age');const keygen=process.env.AGE_KEYGEN_BINARY??resolve(root,'.local/security-tools/age/age-keygen');run(keygen,['-o',resolve(directory,'backup.agekey')]);const recipient=run(keygen,['-y',resolve(directory,'backup.agekey')]).trim();docker('cp',age,pg+':/opt/age');docker('exec',pg,'chmod','755','/opt/age');docker('cp',resolve(root,'infra/ops/base-backup.sh'),pg+':/opt/base-backup.sh');
 await save('backup.mjs','import{execFileSync}from"node:child_process";import{mkdirSync}from"node:fs";const d='+JSON.stringify(resolve(directory,'backup'))+';mkdirSync(d,{recursive:true,mode:0o700});execFileSync("docker",["exec","-e","BACKUP_DIRECTORY=/tmp/release-backup","-e",'+JSON.stringify('AGE_RECIPIENT='+recipient)+',"-e","AGE_BINARY=/opt/age","-e","PGPASSFILE=/tmp/empty-pgpass","-e","PGHOST=/var/run/postgresql","-e","PGUSER=postgres",'+JSON.stringify(pg)+',"sh","-c","touch /tmp/empty-pgpass && chmod 600 /tmp/empty-pgpass && sh /opt/base-backup.sh"],{stdio:"pipe"});execFileSync("docker",["cp",'+JSON.stringify(pg+':/tmp/release-backup/.')+',d],{stdio:"pipe"});\n');
 const base={mode:'local-review',project,release:'old',rustImage:oldRuntime,edgeImage:edge,composeFile:resolve(directory,'compose.yaml'),envFile:resolve(directory,'release.env'),stateDirectory:resolve(directory,'state'),backupDirectory:resolve(directory,'backup'),services,configChecks:[['api','identity-server'],['worker','identity-worker'],['demo-a-bff','demo-bff'],['demo-b-bff','demo-bff']],backup:{program:process.execPath,args:[resolve(directory,'backup.mjs')]},facts:{program:process.execPath,args:[resolve(root,'tests/ops/release-stack.mjs'),'--facts']},smoke:{program:process.execPath,args:[resolve(root,'tests/ops/release-stack-smoke.mjs'),directory]}};
 for(const config of[configuration(base,'local-review'),configuration({...base,release:'new',rustImage:newRuntime},'local-review')]){const result=await runRelease(config,'deploy',{executor:eventExecutor});report.phases.push(result);}
 const current=JSON.parse(await readFile(resolve(directory,'state/current.json'),'utf8'));assert.equal(current.release,'new');const beforeIds=Object.fromEntries(services.map((name)=>[name,docker(...compose(data,['ps','-q',name])).trim()]));const schema=(await facts()).migration_sha256;const checksum=docker('exec',pg,'psql','-U','postgres','-d','identity_test','-Atc',"SELECT encode(checksum,'hex') FROM _sqlx_migrations WHERE version=(SELECT min(version) FROM _sqlx_migrations)").trim();docker('exec',pg,'psql','-U','postgres','-d','identity_test','-c',"UPDATE _sqlx_migrations SET checksum=decode(repeat('00',48),'hex') WHERE version=(SELECT min(version) FROM _sqlx_migrations)");
 let failed=false;try{await runRelease(configuration({...base,release:'invalid-migration',rustImage:newRuntime},'local-review'),'deploy',{executor:eventExecutor});}catch(error){assert.match(error.message,/migrate/u);failed=true;}assert.ok(failed);for(const name of services)assert.equal(docker(...compose(data,['ps','-q',name])).trim(),beforeIds[name]);assert.equal(JSON.parse(await readFile(resolve(directory,'state/current.json'),'utf8')).release,'new');report.phases.push({badMigrationStoppedAllFive:true,containersUnchanged:true});docker('exec',pg,'psql','-U','postgres','-d','identity_test','-c',"UPDATE _sqlx_migrations SET checksum=decode('"+checksum+"','hex') WHERE version=(SELECT min(version) FROM _sqlx_migrations)");assert.equal((await facts()).migration_sha256,schema);
 const compatibility=resolve(directory,'compatibility.json');await save('compatibility.json',JSON.stringify({version:1,from_release:'new',to_release:'old',schema_compatible:true,keys_compatible:true,reason:'Both actual runtimes passed identical current database history and local key map before rollout; previous code schema remains compatible.',old_rust_image:oldRuntime,old_edge_image:edge,accepted_migration_sha256:[schema],old_supported_kids:['stack']}));const rollback=await runRelease(configuration({...base,release:'new',rustImage:newRuntime,compatibilityFile:compatibility},'local-review'),'rollback',{executor:eventExecutor});assert.equal(rollback.stages.some((item)=>item.stage==='migrate'),false);assert.equal(JSON.parse(await readFile(resolve(directory,'state/current.json'),'utf8')).release,'old');report.phases.push(rollback);
 report.sourceSha256={};for(const file of sourceFiles)report.sourceSha256[file]=hash(await readFile(resolve(root,file)));assert.ok(sourceFiles.every((file)=>report.sourceBefore[file]===report.sourceSha256[file]),'Source changed during actual release stack drill.');report.sourceStableDuringRun=true;report.exitCode=0;console.log('Five-service local TLS release/rollback smoke completed.');
}catch(error){report.failure=error.message;if(data){try{const log=docker(...compose(data,['logs','--no-color','--tail','25','api','worker','demo-a-bff','demo-b-bff','edge']));report.safeDiagnostic=log.replaceAll(data.password,'[PASSWORD]').replace(/-----BEGIN[^]*?-----END[^\n]+-----/gu,'[PRIVATE KEY]').replace(/(?:postgres|redis):\/\/[^\s"']+/gu,'[CONNECTION]').replace(/[A-Za-z0-9+/_=-]{43,}/gu,'[OPAQUE]').replace(/[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+/gu,'[EMAIL]');}catch{report.diagnosticUnavailable=true;}}console.error('Five-service local release failed; private evidence retained safely.');process.exitCode=1;}
finally{if(nickname){try{run('certutil',['-D','-d','sql:'+nss,'-n',nickname]);}catch{report.caCleanupFailure=true;report.exitCode=1;process.exitCode=1;}}if(data){try{docker(...compose(data,['down','--volumes']));}catch{report.cleanupFailure=true;report.exitCode=1;process.exitCode=1;}}await rm(directory,{recursive:true,force:true});report.completed=new Date().toISOString();await mkdir(resolve(root,'docs/evidence/T22'),{recursive:true});await writeFile(resolve(root,'docs/evidence/T22/release-stack-'+Date.now()+'.json'),JSON.stringify(report,null,2)+'\n');}

}
