import assert from 'node:assert/strict';import{execFileSync,spawnSync}from'node:child_process';import{createHash}from'node:crypto';import{chmodSync,existsSync,linkSync,mkdirSync,mkdtempSync,readFileSync,renameSync,rmSync,statSync,symlinkSync,writeFileSync}from'node:fs';import{tmpdir}from'node:os';import{join,resolve}from'node:path';import test from'node:test';
const root=resolve(import.meta.dirname,'../..');
test('WAL receipts remain immutable across retries, pointers, legacy objects and hostile paths',async t=>{const fixture=mkdtempSync(join(tmpdir(),'identity-wal-receipt-'));t.after(()=>rmSync(fixture,{recursive:true,force:true}));const archive=join(fixture,'archive');mkdirSync(archive,{mode:0o700});const key=join(fixture,'identity');const age=process.env.AGE_BINARY??'age';const keygen=process.env.AGE_KEYGEN_BINARY??'age-keygen';execFileSync(keygen,['-o',key],{stdio:['ignore','ignore','pipe']});const recipient=execFileSync(keygen,['-y',key],{encoding:'utf8'}).trim();const env={...process.env,WAL_ARCHIVE_DIRECTORY:archive,WAL_ARCHIVE_DEVICE:String(statSync(archive).dev),AGE_BINARY:age,AGE_RECIPIENT:recipient};const source=join(fixture,'source');writeFileSync(source,'synthetic WAL boundary only\n');const one='000000010000000000000001',two='000000010000000000000002';const run=(name=one,overrides={})=>spawnSync('sh',[join(root,'infra/ops/archive-wal.sh'),source,name],{env:{...env,...overrides},encoding:'utf8'});assert.equal(run().status,0);const receipt=readFileSync(join(archive,'last-success.json'),'utf8');const value=JSON.parse(receipt);assert.equal(value.wal_name,one);assert.equal(value.duration_seconds,value.completed_at-value.started_at);assert.equal(value.ciphertext_sha256,createHash('sha256').update(readFileSync(join(archive,one,'wal.age'))).digest('hex'));assert.equal((statSync(join(archive,'last-success.json')).mode&0o777),0o600);
await t.test('same-object retry and older segment never refresh or regress pointer',()=>{assert.equal(run().status,0);assert.equal(readFileSync(join(archive,'last-success.json'),'utf8'),receipt);assert.equal(run(two).status,0);const newer=readFileSync(join(archive,'last-success.json'),'utf8');assert.equal(JSON.parse(newer).wal_name,two);assert.equal(run(one).status,0);assert.equal(readFileSync(join(archive,'last-success.json'),'utf8'),newer);});
await t.test('history and backup-label objects do not refresh full-segment pointer',()=>{const before=readFileSync(join(archive,'last-success.json'),'utf8');assert.equal(run('00000002.history').status,0);assert.equal(run(`${two}.00000000.backup`).status,0);assert.equal(readFileSync(join(archive,'last-success.json'),'utf8'),before);});
await t.test('legacy successful object retry is accepted without inventing a receipt',()=>{const legacy='000000010000000000000000';assert.equal(run(legacy).status,0);writeFileSync(join(archive,'last-success.json'),readFileSync(join(archive,two,'completion.json'),'utf8'));rmSync(join(archive,legacy,'completion.json'));const before=readFileSync(join(archive,'last-success.json'),'utf8');assert.equal(run(legacy).status,0);assert.equal(existsSync(join(archive,legacy,'completion.json')),false);assert.equal(readFileSync(join(archive,'last-success.json'),'utf8'),before);});
await t.test('interrupted pointer durability fails then retry preserves the object completion time',()=>{const tools=join(fixture,'tools');mkdirSync(tools);writeFileSync(join(tools,'sync'),'#!/bin/sh\ncase "$2" in */.archive.lock/pointer.json) exit 1;; esac\nexec /usr/bin/sync "$@"\n',{mode:0o755});const before=readFileSync(join(archive,'last-success.json'),'utf8');const name='000000010000000000000005';assert.notEqual(run(name,{PATH:`${tools}:${process.env.PATH}`}).status,0);const object=readFileSync(join(archive,name,'completion.json'),'utf8');assert.equal(readFileSync(join(archive,'last-success.json'),'utf8'),before);assert.equal(run(name).status,0);assert.equal(readFileSync(join(archive,name,'completion.json'),'utf8'),object);assert.equal(readFileSync(join(archive,'last-success.json'),'utf8'),object);});
await t.test('existing WAL, legacy, history and retained pointers cannot bypass root durability failure',()=>{
 const tools=join(fixture,'root-sync-tools');mkdirSync(tools);const sync=join(tools,'sync');writeFileSync(sync,`#!/bin/sh\nif [ "$2" = "${archive}" ]; then exit 1; fi\nexec /usr/bin/sync "$@"\n`,{mode:0o755});const fault={PATH:`${tools}:${process.env.PATH}`};const pointer=readFileSync(join(archive,'last-success.json'),'utf8');const name='000000010000000000000006';assert.notEqual(run(name,fault).status,0);const receipt=readFileSync(join(archive,name,'completion.json'),'utf8');assert.equal(readFileSync(join(archive,'last-success.json'),'utf8'),pointer);assert.notEqual(run(name,fault).status,0);assert.equal(readFileSync(join(archive,name,'completion.json'),'utf8'),receipt);assert.equal(run(name).status,0);assert.equal(readFileSync(join(archive,'last-success.json'),'utf8'),receipt);
 for(const retry of[name,one,'000000010000000000000000','00000002.history',`${two}.00000000.backup`]){const before=readFileSync(join(archive,'last-success.json'),'utf8');assert.notEqual(run(retry,fault).status,0,`${retry} retry must not skip root sync`);assert.equal(readFileSync(join(archive,'last-success.json'),'utf8'),before);assert.equal(run(retry).status,0);assert.equal(readFileSync(join(archive,'last-success.json'),'utf8'),before);}
});
await t.test('pointer renamed before root sync failure must remain failing while durability is unavailable',()=>{
 const tools=join(fixture,'pointer-root-tools');mkdirSync(tools);const name='000000010000000000000007';writeFileSync(join(tools,'sync'),`#!/bin/sh\nif [ "$2" = "${archive}" ] && [ -f "${archive}/last-success.json" ] && grep -q '"wal_name":"${name}"' "${archive}/last-success.json"; then exit 1; fi\nexec /usr/bin/sync "$@"\n`,{mode:0o755});const fault={PATH:`${tools}:${process.env.PATH}`};assert.notEqual(run(name,fault).status,0);const object=readFileSync(join(archive,name,'completion.json'),'utf8');assert.equal(readFileSync(join(archive,'last-success.json'),'utf8'),object);assert.notEqual(run(name,fault).status,0);assert.equal(readFileSync(join(archive,name,'completion.json'),'utf8'),object);assert.equal(run(name).status,0);assert.equal(readFileSync(join(archive,'last-success.json'),'utf8'),object);
});
await t.test('each retry durability sync failure is propagated instead of being swallowed by later syncs',()=>{
 const tools=join(fixture,'component-sync-tools');mkdirSync(tools);const name='000000010000000000000007';const pointer=readFileSync(join(archive,'last-success.json'),'utf8');const paths=['wal.age','plaintext.sha256','ciphertext.sha256','completion.json'].map(file=>join(archive,name,file)).concat(join(archive,name),join(archive,'last-success.json'),archive);
 for(const target of paths){writeFileSync(join(tools,'sync'),`#!/bin/sh\n[ "$2" != "${target}" ] || exit 1\nexec /usr/bin/sync "$@"\n`,{mode:0o755});assert.notEqual(run(name,{PATH:`${tools}:${process.env.PATH}`}).status,0,`${target} failure must propagate`);assert.equal(readFileSync(join(archive,'last-success.json'),'utf8'),pointer);if(target!==archive&&target!==join(archive,name,'plaintext.sha256')){assert.notEqual(run(one,{PATH:`${tools}:${process.env.PATH}`}).status,0,`${target} retained newer-object sync failure must propagate`);assert.equal(readFileSync(join(archive,'last-success.json'),'utf8'),pointer);}}assert.equal(run(name).status,0);assert.equal(readFileSync(join(archive,'last-success.json'),'utf8'),pointer);
});
await t.test('missing device or unmounted root never creates a fallback',()=>{const absent=join(fixture,'absent');assert.notEqual(run(one,{WAL_ARCHIVE_DEVICE:''}).status,0);assert.notEqual(run(one,{WAL_ARCHIVE_DEVICE:String(BigInt(env.WAL_ARCHIVE_DEVICE)+1n)}).status,0);assert.notEqual(run(one,{WAL_ARCHIVE_DIRECTORY:absent}).status,0);assert.equal(existsSync(absent),false);});
await t.test('writeable group, root ancestors and target symlinks are refused',()=>{chmodSync(archive,0o720);assert.notEqual(run().status,0);chmodSync(archive,0o700);const link=join(fixture,'link');symlinkSync(archive,link);assert.notEqual(run(one,{WAL_ARCHIVE_DIRECTORY:link}).status,0);const target=join(archive,'000000010000000000000004');symlinkSync(join(archive,one),target);assert.notEqual(run('000000010000000000000004').status,0);});
await t.test('pathful or multiple checksums, hardlinks, wrong receipt and corrupt pointer are refused',()=>{const manifest=join(archive,one,'ciphertext.sha256'),original=readFileSync(manifest,'utf8');writeFileSync(manifest,original+original);assert.notEqual(run().status,0);writeFileSync(manifest,original.replace('wal.age','../outside'));assert.notEqual(run().status,0);writeFileSync(manifest,original);linkSync(join(archive,one,'wal.age'),join(fixture,'hardlink'));assert.notEqual(run().status,0);rmSync(join(fixture,'hardlink'));const objectReceipt=join(archive,one,'completion.json'),saved=readFileSync(objectReceipt,'utf8');writeFileSync(objectReceipt,saved.replace(one,two));assert.notEqual(run().status,0);writeFileSync(objectReceipt,saved);const pointer=join(archive,'last-success.json'),before=readFileSync(pointer,'utf8');writeFileSync(pointer,JSON.stringify({...JSON.parse(before),completed_at:Math.floor(Date.now()/1000)+120})+'\n');assert.notEqual(run().status,0);writeFileSync(pointer,before);renameSync(pointer,join(archive,'saved'));symlinkSync(join(fixture,'missing'),pointer);assert.notEqual(run().status,0);rmSync(pointer);renameSync(join(archive,'saved'),pointer);});
});
