import { test, expect, type Page, type BrowserContext } from '@playwright/test';
import { readFile, writeFile } from 'node:fs/promises';
type Scenario = 'users' | 'clients' | 'members' | 'pending';
type Material = { actorId: string; recoveries: string[]; targetId: string; memberId: string; clientDbId: string; memberRecoveries?: string[] };
async function control(path: string, method = 'GET') { const key = process.env.ADMIN_MANAGEMENT_CONTROL_KEY; if (!key) throw new Error('Private management fixture control required.'); const response = await fetch(`http://127.0.0.1:5342/__test/${path}`, { method, headers: { 'x-test-key': key } }); return response; }
async function material(scenario: Scenario): Promise<Material> { const value = await control(`material?scenario=${scenario}`); expect(value.status).toBe(200); return value.json() as Promise<Material>; }
async function login(page: Page, email: string, recovery?: string) { const password = process.env.ADMIN_MANAGEMENT_PASSWORD; if (!password) throw new Error('Private test password required.'); await page.goto('/login'); await page.getByLabel('邮箱地址').fill(email); await page.getByLabel('密码', { exact: true }).fill(password); await page.getByRole('button', { name: '登录', exact: true }).click(); if (recovery) { await page.getByRole('button', { name: '使用恢复码', exact: true }).click(); await page.getByLabel('恢复码', { exact: true }).fill(recovery); await page.getByRole('button', { name: '验证并登录', exact: true }).click(); } await expect(page).toHaveURL(/\/me$/u); }
async function admin(page: Page, scenario: Scenario) { const data = await material(scenario); const code = data.recoveries[0]; if (!code) throw new Error('Actual unused administrator recovery required.'); await login(page, `management-admin-${scenario}@example.test`, code); await page.goto('/admin'); await expect(page.getByRole('heading', { name: '用户管理', exact: true })).toBeVisible(); return data; }
async function proof(page: Page, scenario: Scenario) { const password = process.env.ADMIN_MANAGEMENT_PASSWORD; if (!password) throw new Error('Private password required.'); const dialog = page.getByRole('dialog', { name: '确认当前身份', exact: true }); await expect(dialog).toBeVisible(); await dialog.getByLabel('当前密码', { exact: true }).fill(password); await dialog.getByRole('button', { name: '确认密码', exact: true }).click(); await dialog.getByRole('button', { name: '使用恢复码', exact: true }).click(); const code = (await material(scenario)).recoveries[0]; if (!code) throw new Error('Actual unused strong recovery required.'); await dialog.getByLabel('恢复码', { exact: true }).fill(code); await dialog.getByRole('button', { name: '完成强认证', exact: true }).click(); await expect(dialog).toHaveCount(0); }
async function confirmAction(page: Page, trigger: ReturnType<Page['getByRole']>, scenario: Scenario, confirmName: string) { await trigger.click(); let dialog = page.getByRole('dialog'); await dialog.getByRole('button', { name: '确认身份后继续', exact: true }).click(); await proof(page, scenario); dialog = page.getByRole('dialog'); await dialog.getByRole('button', { name: confirmName, exact: true }).click(); }
async function outcome(name: string, data: unknown) { const file = process.env.ADMIN_MANAGEMENT_RESULT; if (!file) throw new Error('Controlled result file required.'); let results: { name: string; data: unknown }[] = []; try { results = JSON.parse(await readFile(file, 'utf8')) as { name: string; data: unknown }[]; } catch { /* First completed case. */ } results.push({ name, data }); await writeFile(file, JSON.stringify(results, null, 2) + '\n'); }
async function targetLogin(context: BrowserContext) { const page = await context.newPage(); await login(page, 'management-target@example.test'); return page; }

test('user disable, enable and global session revocation use real authority', async ({ page, browser }) => {
  const otherContext = await browser.newContext(); try { const other = await targetLogin(otherContext); const data = await admin(page, 'users'); await page.getByLabel('完整邮箱').fill('management-target@example.test'); await page.getByRole('button', { name: '查询用户', exact: true }).click(); const row = page.getByRole('row').filter({ hasText: 'management-target@example.test' }); await row.getByRole('button', { name: '查看用户', exact: true }).click();
    const disabled = page.waitForResponse((response) => response.request().method() === 'PATCH' && new URL(response.url()).pathname.endsWith(`/users/${data.targetId}/status`)); await confirmAction(page, page.getByRole('button', { name: '禁用账号', exact: true }), 'users', '确认禁用账号'); expect((await disabled).status()).toBe(200); await expect(page.getByRole('button', { name: '启用账号', exact: true })).toBeVisible(); expect((await other.request.get('/api/v1/me')).status()).toBe(401);
    const enabled = page.waitForResponse((response) => response.request().method() === 'PATCH' && new URL(response.url()).pathname.endsWith(`/users/${data.targetId}/status`)); await confirmAction(page, page.getByRole('button', { name: '启用账号', exact: true }), 'users', '确认启用账号'); expect((await enabled).status()).toBe(200); await expect(page.getByRole('button', { name: '禁用账号', exact: true })).toBeVisible(); await login(other, 'management-target@example.test'); expect((await other.request.get('/api/v1/me')).status()).toBe(200);
    const revoked = page.waitForResponse((response) => response.request().method() === 'POST' && new URL(response.url()).pathname.endsWith('/revoke-sessions')); await confirmAction(page, page.getByRole('button', { name: '撤销全部会话', exact: true }), 'users', '确认撤销全部会话'); expect((await revoked).status()).toBe(200); expect((await other.request.get('/api/v1/me')).status()).toBe(401); const detail = await page.request.get(`/api/v1/admin/users/${data.targetId}`); expect(detail.status()).toBe(200); const user = await detail.json() as { status: string }; expect(user.status).toBe('active'); await outcome('users', { actualDisableRejectsOldSession: true, actualEnableAllowsFreshLogin: true, actualRevokeRemovesSession: true });
  } finally { await otherContext.close(); }
});

test('client exact callback editing and disable enable persist through real API', async ({ page }) => {
  const data = await admin(page, 'clients'); await page.getByRole('button', { name: '应用客户端', exact: true }).click(); const row = page.getByRole('row').filter({ hasText: 'management-client' }); await row.getByRole('button', { name: '编辑客户端', exact: true }).click(); await page.getByLabel('应用名称').fill('Management edited client'); await page.getByLabel('登录回调地址（每行一个）').fill('http://localhost:5340/callback\nhttp://localhost:5340/other-callback'); await page.getByLabel('退出回调地址（每行一个）').fill('http://localhost:5340/signed-out'); await page.getByRole('button', { name: '保存客户端', exact: true }).click(); await proof(page, 'clients'); const updated = page.waitForResponse((response) => response.request().method() === 'PATCH' && new URL(response.url()).pathname.endsWith(`/clients/${data.clientDbId}`)); await page.getByRole('button', { name: '保存客户端', exact: true }).click(); expect((await updated).status()).toBe(200); const edited = page.getByRole('row').filter({ hasText: 'Management edited client' }); await expect(edited).toBeVisible();
  await confirmAction(page, edited.getByRole('button', { name: '停用客户端', exact: true }), 'clients', '确认停用客户端'); await expect(edited.getByRole('button', { name: '启用客户端', exact: true })).toBeVisible(); await confirmAction(page, edited.getByRole('button', { name: '启用客户端', exact: true }), 'clients', '确认启用客户端'); await expect(edited.getByRole('button', { name: '停用客户端', exact: true })).toBeVisible(); const actual = await page.request.get('/api/v1/admin/clients?limit=20'); expect(actual.status()).toBe(200); const value = await actual.json() as { items: { id: string; name: string; enabled: boolean; redirect_uris: string[]; post_logout_redirect_uris: string[] }[] }; const client = value.items.find((item) => item.id === data.clientDbId); expect(client).toMatchObject({ name: 'Management edited client', enabled: true, redirect_uris: ['http://localhost:5340/callback', 'http://localhost:5340/other-callback'], post_logout_redirect_uris: ['http://localhost:5340/signed-out'] }); await outcome('clients', { editedExactCallbacks: true, disabledEnabledPersisted: true });
});

test('member grant remove and last-administrator guard preserve access', async ({ page, browser }) => {
  const memberContext = await browser.newContext(); try { const data = await admin(page, 'members'); const candidate = await memberContext.newPage(); const recovery = data.memberRecoveries?.[0]; if (!recovery) throw new Error('Actual candidate recovery required.'); await login(candidate, 'management-member@example.test', recovery); expect((await candidate.request.get('/api/v1/admin/members?limit=20')).status()).toBe(403); await page.getByRole('button', { name: '管理员', exact: true }).click(); await page.getByLabel('已有用户ID').fill(data.memberId); await confirmAction(page, page.getByRole('button', { name: '授予管理员', exact: true }), 'members', '确认授予管理员'); const row = page.getByRole('row').filter({ hasText: 'management-member@example.test' }); await expect(row).toBeVisible(); expect((await candidate.request.get('/api/v1/admin/members?limit=20')).status()).toBe(200);
    const removed = page.waitForResponse((response) => response.request().method() === 'DELETE' && new URL(response.url()).pathname.endsWith(`/members/${data.memberId}`)); await confirmAction(page, row.getByRole('button', { name: '移除管理员', exact: true }), 'members', '确认移除管理员'); expect((await removed).status()).toBe(204); await expect(page.getByRole('dialog')).toHaveCount(0); await expect(row).toHaveCount(0); expect((await candidate.request.get('/api/v1/admin/members?limit=20')).status()).toBe(403);
    expect((await control('setup-last-admin?scenario=members', 'POST')).status).toBe(200); await page.reload(); await page.getByRole('button', { name: '管理员', exact: true }).click(); const actor = page.getByRole('row').filter({ hasText: 'management-admin-members@example.test' }); const guarded = page.waitForResponse((response) => response.request().method() === 'DELETE' && new URL(response.url()).pathname.endsWith(`/members/${data.actorId}`)); await confirmAction(page, actor.getByRole('button', { name: '移除管理员', exact: true }), 'members', '确认移除管理员'); const denied = await guarded; expect(denied.status()).toBe(409); const failure = await denied.json() as { error: { code: string } }; expect(failure.error.code).toBe('ADMIN_LAST_MEMBER'); const error = page.getByRole('alert').filter({ hasText: '需要先保留另一位合格管理员' }); await expect(error).toBeVisible(); await page.getByRole('dialog').getByRole('button', { name: '取消', exact: true }).click(); expect((await page.request.get('/api/v1/admin/members?limit=20')).status()).toBe(200); await outcome('members', { actualGrantAllowsAdminApi: true, actualRemoveRejectsAdminApi: true, lastAdminRejectedAndStillManageable: true, lastAdminStatus: 409, lastAdminCode: 'ADMIN_LAST_MEMBER' });
  } finally { await control('restore-admins?scenario=members', 'POST'); await memberContext.close(); }
});

test('pending client mutation is single request and cannot be canceled or duplicated', async ({ page }) => {
  const data = await admin(page, 'pending'); await page.getByRole('button', { name: '应用客户端', exact: true }).click(); const row = page.getByRole('row').filter({ hasText: 'management-pending-client' }); await row.getByRole('button', { name: '停用客户端', exact: true }).click(); await page.getByRole('dialog').getByRole('button', { name: '确认身份后继续', exact: true }).click(); await proof(page, 'pending'); expect((await control('hold?scenario=pending&operation=disable-client', 'POST')).status).toBe(200); let mutations = 0; page.on('request', (request) => { if (request.method() === 'PATCH' && new URL(request.url()).pathname.endsWith(`/clients/${data.clientDbId}`)) mutations += 1; });
  try { const dialog = page.getByRole('dialog'); const confirm = dialog.getByRole('button', { name: '确认停用客户端', exact: true }); const actual = page.waitForResponse((response) => response.request().method() === 'PATCH' && new URL(response.url()).pathname.endsWith(`/clients/${data.clientDbId}`)); await confirm.click(); const pending = dialog.getByRole('button', { name: '正在处理…', exact: true }); await expect(pending).toBeDisabled(); await expect(dialog.getByRole('button', { name: '取消', exact: true })).toBeDisabled(); await expect.poll(async () => (await (await control('held?scenario=pending&operation=disable-client')).json() as { blockedMutations: number }).blockedMutations).toBeGreaterThan(0); const before = await (await control('held?scenario=pending&operation=disable-client')).json() as { enabled: boolean; clientUpdateCount: number }; expect(before).toMatchObject({ enabled: true, clientUpdateCount: 0 }); const position = await pending.boundingBox(); if (!position) throw new Error('Actual pending button must remain visible.'); await page.mouse.click(position.x + position.width / 2, position.y + position.height / 2, { clickCount: 2 }); await page.keyboard.press('Enter'); await page.keyboard.press('Escape'); await expect(dialog).toBeVisible(); expect(mutations).toBe(1); expect((await control('release?scenario=pending&operation=disable-client', 'POST')).status).toBe(200); expect((await actual).status()).toBe(200); await expect(dialog).toHaveCount(0); await expect(row.getByRole('button', { name: '启用客户端', exact: true })).toBeVisible(); expect(mutations).toBe(1); const after = await (await control('held?scenario=pending&operation=disable-client')).json() as { enabled: boolean; clientUpdateCount: number }; expect(after).toMatchObject({ enabled: false, clientUpdateCount: 1 }); await outcome('pending', { realDatabaseLockObserved: true, disabledSubmitAndCancel: true, repeatedPointerAndEnterIgnored: true, escapeBlockedWhilePending: true, actualMutationRequests: mutations, committedAuditEvents: after.clientUpdateCount });
  } finally { await control('release?scenario=pending&operation=disable-client', 'POST'); }
});
