import { test, expect, type Browser, type Page, type Locator } from '@playwright/test';
import { createHash } from 'node:crypto';
import { readFile, writeFile } from 'node:fs/promises';
import { chromium } from 'playwright';

const settings = { chrome: 'HeadlessChrome/153.0.8010.12', viewport: { width: 390, height: 844 }, samples: 5, cpuSlowdown: 4, downloadBytesPerSecond: 200000, uploadBytesPerSecond: 93750, latencyMs: 150 };
type Sample = { mode: string; scenario: string; sample: number; feedbackMs: number; completionMs: number; eventTiming: { durationMs: number | null; censoredBelow16Ms: boolean; eventCount: number; interactionIds: number[] }; backendVerified: boolean; status?: number; apiDurationMs?: number; pageIdsChanged?: boolean };
async function privateMaterial(query: string): Promise<{ recoveries?: string[]; devices?: { name: string; token: string }[] }> { const key = process.env.T23_ACCESSIBILITY_CLOCK_KEY; if (!key) throw new Error('Private fixture control required.'); const response = await fetch(`http://127.0.0.1:5322/__test/material?${query}`, { headers: { 'x-test-key': key } }); expect(response.status).toBe(200); return response.json() as Promise<{ recoveries?: string[]; devices?: { name: string; token: string }[] }>; }
async function login(page: Page, email: string, admin: boolean) { const password = process.env.T23_ACCESSIBILITY_BROWSER_PASSWORD; if (!password) throw new Error('Private fixture password required.'); await page.goto('/login'); await page.getByLabel('邮箱地址').fill(email); await page.getByLabel('密码', { exact: true }).fill(password); await page.getByRole('button', { name: '登录', exact: true }).click(); if (admin) { await page.getByRole('button', { name: '使用恢复码', exact: true }).click(); const recovery = (await privateMaterial('browser=dialogs-chromium')).recoveries?.[0]; if (!recovery) throw new Error('Unused real admin recovery proof required.'); await page.getByLabel('恢复码', { exact: true }).fill(recovery); await page.getByRole('button', { name: '验证并登录', exact: true }).click(); } await expect(page).toHaveURL(/\/me$/u); }
async function ready(page: Page) { await expect(page.locator('main h1')).toBeVisible(); await expect(page.locator('main [aria-busy="true"]')).toHaveCount(0); await expect(page.locator('main').getByRole('status').filter({ hasText: /暂时无法|正在加载|正在查询|正在读取/u })).toHaveCount(0); }
async function prepare(trigger: Locator, feedback: string, completion: string) {
  await trigger.scrollIntoViewIfNeeded(); await trigger.evaluate((element, predicates) => {
    const win = window as Window & { __interaction?: { done: boolean; started: number; finished: number; feedbackMs: number; completionMs: number; trusted: boolean; entries: { name: string; startTime: number; duration: number; interactionId: number }[]; observer: PerformanceObserver } };
    const visible = (expression: string) => { const [selector, text] = expression.split('@text='); if (!selector) return false; return Array.from(document.querySelectorAll(selector)).some((node) => node.getBoundingClientRect().width > 0 && node.getBoundingClientRect().height > 0 && (text === undefined || node.textContent === text)); };
    const matches = (selector: string): boolean => selector.split('||').some((part) => part.startsWith('!') ? !visible(part.slice(1)) : visible(part));
    const entries: { name: string; startTime: number; duration: number; interactionId: number }[] = [];
    const observer = new PerformanceObserver((list) => { for (const item of list.getEntries()) { const event = item as PerformanceEventTiming; entries.push({ name: event.name, startTime: event.startTime, duration: event.duration, interactionId: event.interactionId }); } }); observer.observe({ type: 'event', buffered: false, durationThreshold: 16 } as PerformanceObserverInit & { durationThreshold: number });
    const state = { done: false, started: 0, finished: 0, feedbackMs: 0, completionMs: 0, trusted: false, entries, observer }; win.__interaction = state;
    element.addEventListener('click', (event) => { state.started = event.timeStamp; state.trusted = event.isTrusted; let feedbackScheduled = false; let completionScheduled = false;
      const tick = () => {
        if (!feedbackScheduled && matches(predicates.feedback)) { feedbackScheduled = true; requestAnimationFrame(() => { requestAnimationFrame(() => { state.feedbackMs = performance.now() - state.started; }); }); }
        if (!completionScheduled && matches(predicates.completion)) { completionScheduled = true; requestAnimationFrame(() => { requestAnimationFrame(() => { state.completionMs = performance.now() - state.started; state.finished = performance.now(); state.done = true; }); }); }
        if (!state.done) requestAnimationFrame(tick);
      }; requestAnimationFrame(tick);
    }, { once: true, capture: true });
  }, { feedback, completion });
}
async function finish(page: Page) {
  await expect.poll(() => page.evaluate(() => (window as Window & { __interaction?: { done: boolean } }).__interaction?.done), { timeout: 15_000 }).toBe(true);
  // EventTiming observer callbacks arrive asynchronously after presentation; collect all entries for this input group.
  await page.waitForTimeout(80);
  return page.evaluate(() => {
    const state = (window as Window & { __interaction?: { started: number; finished: number; feedbackMs: number; completionMs: number; trusted: boolean; entries: { name: string; startTime: number; duration: number; interactionId: number }[]; observer: PerformanceObserver } }).__interaction;
    if (!state?.trusted || !state.feedbackMs || !state.completionMs) throw new Error('A trusted input and actual visible feedback are required.');
    for (const item of state.observer.takeRecords()) { const event = item as PerformanceEventTiming; state.entries.push({ name: event.name, startTime: event.startTime, duration: event.duration, interactionId: event.interactionId }); } state.observer.disconnect();
    const events = state.entries.filter((event) => event.interactionId > 0 && event.startTime >= state.started - 100 && event.startTime <= state.started + 1); const ids = [...new Set(events.map((event) => event.interactionId))];
    return { feedbackMs: state.feedbackMs, completionMs: state.completionMs, eventTiming: { durationMs: events.length ? Math.max(...events.map((event) => event.duration)) : null, censoredBelow16Ms: events.length === 0, eventCount: events.length, interactionIds: ids } };
  });
}
async function measure(page: Page, trigger: Locator, feedback: string, completion: string) { await prepare(trigger, feedback, completion); await trigger.click(); return finish(page); }
async function resourceDuration(page: Page, path: string) { return page.evaluate(({ path }) => { const entries = performance.getEntriesByType('resource') as PerformanceResourceTiming[]; const selected = entries.filter((entry) => new URL(entry.name).pathname.startsWith(path) && entry.initiatorType === 'fetch'); const found = selected.at(-1); if (!found) throw new Error('Actual API ResourceTiming entry required.'); return found.duration; }, { path }); }
async function pageFor(browser: Browser, mode: string) { const context = await browser.newContext({ viewport: settings.viewport, serviceWorkers: 'block' }); const page = await context.newPage(); const cdp = await context.newCDPSession(page); await cdp.send('Network.enable'); await cdp.send('Network.clearBrowserCache'); await cdp.send('Network.setCacheDisabled', { cacheDisabled: true }); await cdp.send('Emulation.setCPUThrottlingRate', { rate: mode === 'laboratory' ? 4 : 1 }); if (mode === 'laboratory') await cdp.send('Network.emulateNetworkConditions', { offline: false, latency: 150, downloadThroughput: 200000, uploadThroughput: 93750, connectionType: 'cellular3g' }); return { context, page, cdp }; }
const percentile = (values: number[]) => { const value = [...values].sort((a, b) => a - b)[Math.ceil(values.length * .75) - 1]; if (value === undefined) throw new Error('Five actual samples required.'); return value; };

test('real account and administrator interaction latency', async ({ browser }) => {
  const probe = await browser.newContext(); const versionPage = await probe.newPage(); const versionCdp = await probe.newCDPSession(versionPage); const version = await versionCdp.send('Browser.getVersion'); expect(version.product).toBe(settings.chrome); await probe.close(); const samples: Sample[] = []; const requestedResult = process.env.PRODUCT_INTERACTIONS_RESULT; if (!requestedResult) throw new Error('Private result path required.'); const resultFile: string = requestedResult; async function record(sample: Sample) { samples.push(sample); await writeFile(resultFile, JSON.stringify({ settings, browser: version, samples, partial: true }) + '\n'); }
  for (const mode of ['local', 'laboratory']) {
    const { context, page, cdp } = await pageFor(browser, mode); try {
      await login(page, `performance-account-${mode}@example.test`, false); await ready(page);
      let logoutRequests = 0; page.on('request', (request) => { if (new URL(request.url()).pathname.endsWith('/auth/logout')) logoutRequests += 1; });
      for (let sample = 1; sample <= 5; sample += 1) {
        const open = await measure(page, page.getByRole('button', { name: '退出当前设备', exact: true }), '[role="dialog"] button', '[role="dialog"] button'); await expect(page.getByRole('button', { name: '取消', exact: true })).toBeFocused(); await record({ mode, scenario: 'account-dialog-open', sample, ...open, backendVerified: true });
        const cancel = await measure(page, page.getByRole('button', { name: '取消', exact: true }), '![role="dialog"]', '![role="dialog"]'); await record({ mode, scenario: 'account-dialog-cancel', sample, ...cancel, backendVerified: true });
      } expect(logoutRequests).toBe(0); expect((await page.request.get('/api/v1/me')).status()).toBe(200);
      for (let sample = 1; sample <= 5; sample += 1) {
        const firstResponse = page.waitForResponse((value) => new URL(value.url()).pathname === '/api/v1/me/sessions' && !new URL(value.url()).searchParams.has('cursor')); await page.goto('/me/sessions'); await ready(page); const firstBody = await (await firstResponse).json() as { items: { id: string }[] }; const before = await page.locator('tbody tr').count(); expect(before).toBe(20); const response = page.waitForResponse((value) => new URL(value.url()).pathname === '/api/v1/me/sessions' && new URL(value.url()).searchParams.has('cursor'));
        const measured = await measure(page, page.getByRole('button', { name: '下一页', exact: true }), '.status[aria-busy="true"]||tbody tr:nth-child(7):last-child', 'tbody tr:nth-child(7):last-child'); const actual = await response; expect(actual.status()).toBe(200); const body = await actual.json() as { items: { id: string }[] }; expect(body.items).toHaveLength(7); expect(body.items.some((item) => firstBody.items.some((prior) => prior.id === item.id))).toBe(false); expect(await page.locator('tbody tr').count()).toBe(7); const apiDurationMs = await resourceDuration(page, '/api/v1/me/sessions'); await record({ mode, scenario: 'sessions-next-page', sample, ...measured, backendVerified: true, status: 200, apiDurationMs, pageIdsChanged: true });
      }
      const devices = (await privateMaterial(`performance=${mode}`)).devices; if (!devices || devices.length !== 5) throw new Error('Five actual noncurrent sessions are required.');
      for (let sample = 1; sample <= 5; sample += 1) {
        const device = devices[sample - 1]; if (!device) throw new Error('Actual session sample missing.'); expect((await page.request.get('/api/v1/me', { headers: { cookie: `identity-dev=${device.token}` } })).status()).toBe(200); await page.goto('/me/sessions'); await ready(page); const row = page.getByRole('row').filter({ hasText: device.name }); await row.getByRole('button', { name: '撤销会话', exact: true }).click(); const response = page.waitForResponse((value) => value.request().method() === 'DELETE' && new URL(value.url()).pathname.startsWith('/api/v1/me/sessions/'));
        const measured = await measure(page, page.getByRole('dialog').getByRole('button', { name: '确认撤销', exact: true }), '[role="dialog"] [aria-busy="true"]||![role="dialog"]', '![role="dialog"]'); expect((await response).status()).toBe(204); await expect(row).toHaveCount(0); expect((await page.request.get('/api/v1/me', { headers: { cookie: `identity-dev=${device.token}` } })).status()).toBe(401); expect((await page.request.get('/api/v1/me')).status()).toBe(200); await record({ mode, scenario: 'session-revocation-confirm', sample, ...measured, backendVerified: true, status: 204, apiDurationMs: await resourceDuration(page, '/api/v1/me/sessions/') });
      }
    } finally { await cdp.detach(); await context.close(); }
    const admin = await pageFor(browser, mode); try {
      await login(admin.page, 'access-admin-dialogs-chromium@example.test', true); await admin.page.goto('/admin'); await ready(admin.page);
      for (let sample = 1; sample <= 5; sample += 1) {
        await admin.page.getByRole('button', { name: '用户', exact: true }).click(); await ready(admin.page); const response = admin.page.waitForResponse((value) => new URL(value.url()).pathname === '/api/v1/admin/clients'); const measured = await measure(admin.page, admin.page.getByRole('button', { name: '应用客户端', exact: true }), '.admin-navigation button[aria-current="page"]:nth-child(2)', 'table caption@text=客户端列表'); const actual = await response; expect(actual.status()).toBe(200); await actual.finished(); await ready(admin.page); await record({ mode, scenario: 'admin-client-navigation', sample, ...measured, backendVerified: true, status: 200, apiDurationMs: await resourceDuration(admin.page, '/api/v1/admin/clients') });
        const validated = await measure(admin.page, admin.page.getByRole('button', { name: '创建客户端', exact: true }), '[role="alert"]', '[role="alert"]'); await expect(admin.page.getByRole('alert')).toBeVisible(); await record({ mode, scenario: 'admin-client-local-validation', sample, ...validated, backendVerified: true });
      }
    } finally { await admin.cdp.detach(); await admin.context.close(); }
  }
  const summaries = []; for (const mode of ['local', 'laboratory']) for (const scenario of [...new Set(samples.map((sample) => sample.scenario))]) { const selected = samples.filter((sample) => sample.mode === mode && sample.scenario === scenario); expect(selected).toHaveLength(5); const latency = mode === 'local' ? Math.max(...selected.map((sample) => sample.feedbackMs)) : percentile(selected.map((sample) => sample.feedbackMs)); summaries.push({ mode, scenario, samples: 5, feedbackStatistic: mode === 'local' ? 'maximum' : 'nearest-rank p75', feedbackMs: latency, thresholdMs: mode === 'local' ? 100 : 200, met: latency <= (mode === 'local' ? 100 : 200), completionP75Ms: percentile(selected.map((sample) => sample.completionMs)), eventTimingValidSamples: selected.filter((sample) => sample.eventTiming.durationMs !== null).length, eventTimingP75Ms: selected.every((sample) => sample.eventTiming.durationMs !== null) ? percentile(selected.map((sample) => sample.eventTiming.durationMs ?? 0)) : null }); }
  const file = process.env.PRODUCT_INTERACTIONS_RESULT; if (!file) throw new Error('Private result path required.'); await writeFile(file, JSON.stringify({ settings, browser: version, browserExecutableSha256: createHash('sha256').update(await readFile(chromium.executablePath())).digest('hex'), methodology: { feedback: 'Trusted click timestamp to earliest visible feedback plus two rAF callbacks; paint proxy, not exact pixel paint or INP.', completion: 'Same browser timestamp to actual result state plus two rAF; async network duration separate and has no 200ms business completion budget.', eventTiming: '16ms observer threshold; 8ms quantized event group max; missing entries are censored, not zero.', cache: 'new context per mode, browser cache disabled, production assets gzip; route navigation resets scenario state', data: '26 real canonical repository sessions per mode plus actual browser login; five revocations, independent mode users; complete standard administrator MFA recovery set.' }, samples, summaries }, null, 2) + '\n'); expect(summaries.filter((summary) => !summary.met).map((summary) => ({ mode: summary.mode, scenario: summary.scenario, feedbackMs: summary.feedbackMs }))).toEqual([]);
});
