import { test, expect, type Page } from '@playwright/test';
import { createHmac } from 'node:crypto';
async function material(): Promise<{ secret: string; seconds: number; recoveries: string[] }> { const key = process.env.T19_CLOCK_KEY; if (!key) throw new Error('Private test key required.'); return (await fetch('http://127.0.0.1:5197/__test/material?advance=1', { headers: { 'x-test-key': key } })).json() as Promise<{ secret: string; seconds: number; recoveries: string[] }>; }
function totp(secret: string, seconds: number): string { let bits = 0, buffer = 0; const bytes: number[] = []; for (const letter of secret) { buffer = buffer << 5 | 'ABCDEFGHIJKLMNOPQRSTUVWXYZ234567'.indexOf(letter); bits += 5; if (bits >= 8) { bits -= 8; bytes.push(buffer >> bits & 255); buffer &= (1 << bits) - 1; } } const counter = Buffer.alloc(8); counter.writeBigUInt64BE(BigInt(Math.floor(seconds / 30))); const digest = createHmac('sha1', Buffer.from(bytes)).update(counter).digest(); return String((digest.readUInt32BE((digest[19] ?? 0) & 15) & 0x7fffffff) % 1_000_000).padStart(6, '0'); }
async function adminLogin(page: Page) { const password = process.env.T19_BROWSER_PASSWORD; if (!password) throw new Error('Private test password required.'); await page.goto('/login'); await page.getByLabel('邮箱地址').fill('browser-admin@example.test'); await page.getByLabel('密码', { exact: true }).fill(password); await page.getByRole('button', { name: '登录', exact: true }).click(); const value = await material(); await page.getByLabel('验证码', { exact: true }).fill(totp(value.secret, value.seconds)); await page.getByRole('button', { name: '验证并登录', exact: true }).click(); await expect(page).toHaveURL(/\/me$/u); await page.goto('/admin'); if (await page.getByRole('button', { name: '确认当前身份', exact: true }).isVisible()) { await page.getByRole('button', { name: '确认当前身份', exact: true }).click(); await confirm(page); } await expect(page.getByRole('heading', { name: '用户管理', exact: true })).toBeVisible(); }
let recoveryIndex = 0;
async function confirm(page: Page) {
  const dialog = page.getByRole('dialog', { name: '确认当前身份' }); const password = process.env.T19_BROWSER_PASSWORD; if (!password) throw new Error('Private test password required.');
  await dialog.getByLabel('当前密码', { exact: true }).fill(password); await dialog.getByRole('button', { name: '确认密码', exact: true }).click();
  const value = await material(); const recovery = value.recoveries[recoveryIndex++]; if (!recovery) throw new Error('Unused recovery proof missing.');
  await dialog.getByRole('button', { name: '使用恢复码', exact: true }).click(); await dialog.getByLabel('恢复码', { exact: true }).fill(recovery); await dialog.getByRole('button', { name: '完成强认证', exact: true }).click(); await expect(dialog).toHaveCount(0);
}

test('@T19 client secrets appear once and malicious names remain text', async ({ page }) => {
  await adminLogin(page); await page.getByRole('button', { name: '应用客户端', exact: true }).click(); await expect(page.getByRole('heading', { name: '应用客户端', exact: true })).toBeVisible();
  const name = '<img src=x onerror=alert(1)>'; await page.getByLabel('应用名称', { exact: true }).fill(name); await page.getByLabel('登录回调地址（每行一个）').fill('http://localhost:5190/callback'); await page.getByRole('button', { name: '创建客户端', exact: true }).click(); await confirm(page); await page.getByRole('button', { name: '创建客户端', exact: true }).click();
  const secret = page.getByRole('dialog', { name: '保存客户端秘密' }); await expect(secret).toBeVisible(); const value = await secret.locator('.setup-secret').textContent(); if (!value) throw new Error('Generated client secret is missing.'); await secret.getByRole('button', { name: '已保存，关闭秘密', exact: true }).click(); await expect(secret).toHaveCount(0); expect(await page.locator('main').innerText()).not.toContain(value); await expect(page.getByText(name, { exact: true })).toBeVisible(); expect(await page.locator('img[onerror]').count()).toBe(0);
  await page.getByRole('row').filter({ hasText: name }).getByRole('button', { name: '轮换客户端秘密', exact: true }).click(); await page.getByRole('dialog').getByRole('button', { name: '确认身份后继续', exact: true }).click(); await confirm(page); await page.getByRole('dialog').getByRole('button', { name: '确认轮换客户端秘密', exact: true }).click(); await expect(page.getByRole('dialog', { name: '保存客户端秘密' })).toBeVisible(); await page.getByRole('button', { name: '已保存，关闭秘密', exact: true }).click();
});

test('@T19 ordinary users receive no administrator data', async ({ page }) => {
  const password = process.env.T19_BROWSER_PASSWORD; if (!password) throw new Error('Private password required.'); await page.goto('/login'); await page.getByLabel('邮箱地址').fill('browser-devices@example.test'); await page.getByLabel('密码', { exact: true }).fill(password); await page.getByRole('button', { name: '登录', exact: true }).click(); await expect(page).toHaveURL(/\/me$/u); await page.goto('/admin'); await expect(page.getByText('无法访问管理后台', { exact: true })).toBeVisible(); const status = await page.evaluate(async () => (await fetch('/api/v1/admin/users', { credentials: 'same-origin' })).status); expect(status).toBe(403);
});

test('@T19 hundred-thousand-user pages use actual cursor requests and bounded audit windows', async ({ page }) => {
  await adminLogin(page); const table = page.getByRole('table', { name: '用户列表' }); await expect(table).toBeVisible(); expect(await table.locator('tbody tr').count()).toBeLessThanOrEqual(20);
  const next = page.waitForResponse((response) => response.url().includes('/admin/users?') && new URL(response.url()).searchParams.has('cursor')); await page.getByRole('button', { name: '下一页', exact: true }).click(); const result = await next; expect(result.status()).toBe(200);
  await page.getByRole('button', { name: '安全审计', exact: true }).click(); await expect(page.getByRole('heading', { name: '安全审计', exact: true })).toBeVisible(); const end = new Date(); const start = new Date(end.getTime() - 32 * 86_400_000); await page.getByLabel('开始时间（RFC3339）').fill(start.toISOString()); await page.getByLabel('结束时间（RFC3339）').fill(end.toISOString()); await page.getByRole('button', { name: '查询审计', exact: true }).click(); await expect(page.getByRole('alert').filter({ hasText: '31天' })).toBeVisible();
});
