[package]
name = "identity-admin-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
identity-core = { path = "../identity-core" }
identity-store = { path = "../identity-store" }
rpassword.workspace = true
sqlx.workspace = true
tokio.workspace = true
uuid.workspace = true
zeroize.workspace = true

[lints]
workspace = true
