-- T03 schema baseline. Security rules and single-use operations stay in services/transactions.
-- UUIDs are generated by the application, never chosen as identity by a browser request.

CREATE TABLE users (
    id UUID PRIMARY KEY,
    email TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    display_name TEXT,
    verified BOOLEAN NOT NULL DEFAULT FALSE,
    status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'disabled')),
    credential_version BIGINT NOT NULL DEFAULT 1 CHECK (credential_version >= 1),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT users_email_normalized CHECK (
        email = lower(btrim(email))
        AND octet_length(email) = char_length(email)
        AND char_length(email) BETWEEN 3 AND 254
        AND char_length(split_part(email, '@', 1)) BETWEEN 1 AND 64
        AND email ~ '^[a-z0-9.!#$%&''*+/=?^_`{|}~-]+@[a-z0-9]([a-z0-9-]*[a-z0-9])?(\.[a-z0-9]([a-z0-9-]*[a-z0-9])?)*$'
        AND email !~ '[[:cntrl:][:space:]]'
    ),
    CONSTRAINT users_password_hash_nonempty CHECK (char_length(password_hash) BETWEEN 1 AND 1024),
    CONSTRAINT users_display_name_length CHECK (display_name IS NULL OR char_length(display_name) BETWEEN 1 AND 200),
    CONSTRAINT users_timestamps CHECK (updated_at >= created_at)
);

CREATE TABLE sessions (
    id UUID PRIMARY KEY,
    token_hash BYTEA NOT NULL UNIQUE CHECK (octet_length(token_hash) = 32),
    user_id UUID NOT NULL REFERENCES users(id),
    amr TEXT[] NOT NULL CHECK (cardinality(amr) > 0 AND amr <@ ARRAY['pwd', 'otp', 'rcv', 'user', 'hwk']::TEXT[]),
    auth_time TIMESTAMPTZ NOT NULL,
    strong_at TIMESTAMPTZ,
    csrf_hash BYTEA NOT NULL CHECK (octet_length(csrf_hash) = 32),
    credential_version BIGINT NOT NULL CHECK (credential_version >= 1),
    user_agent TEXT NOT NULL DEFAULT '' CHECK (char_length(user_agent) <= 256),
    expires_at TIMESTAMPTZ NOT NULL,
    revoked_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (id, user_id),
    CHECK (expires_at > created_at AND expires_at <= auth_time + INTERVAL '12 hours'),
    CHECK (auth_time <= created_at),
    CHECK (strong_at IS NULL OR (strong_at >= auth_time AND strong_at < expires_at)),
    CHECK (revoked_at IS NULL OR revoked_at >= created_at)
);
CREATE INDEX sessions_active_user_idx ON sessions(user_id, expires_at, id) WHERE revoked_at IS NULL;
CREATE INDEX sessions_expiry_idx ON sessions(expires_at, id);

CREATE TABLE oauth_clients (
    id UUID PRIMARY KEY,
    client_id TEXT NOT NULL UNIQUE CHECK (char_length(client_id) BETWEEN 1 AND 128),
    secret_hash BYTEA NOT NULL CHECK (octet_length(secret_hash) = 32),
    name TEXT NOT NULL CHECK (char_length(name) BETWEEN 1 AND 200),
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    allowed_scopes TEXT[] NOT NULL CHECK (cardinality(allowed_scopes) > 0 AND allowed_scopes <@ ARRAY['openid', 'profile', 'email']::TEXT[]),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (updated_at >= created_at)
);

CREATE TABLE oauth_redirect_uris (
    id UUID PRIMARY KEY,
    client_id UUID NOT NULL REFERENCES oauth_clients(id),
    uri TEXT NOT NULL CHECK (char_length(uri) BETWEEN 1 AND 2048 AND uri !~ '[[:cntrl:][:space:]]' AND position('*' IN uri) = 0),
    kind TEXT NOT NULL CHECK (kind IN ('login', 'logout')),
    UNIQUE (client_id, uri, kind)
);

CREATE TABLE oauth_grants (
    id UUID PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES users(id),
    client_id UUID NOT NULL REFERENCES oauth_clients(id),
    session_id UUID NOT NULL,
    scopes TEXT[] NOT NULL CHECK (cardinality(scopes) > 0 AND scopes <@ ARRAY['openid', 'profile', 'email']::TEXT[] AND 'openid' = ANY(scopes)),
    expires_at TIMESTAMPTZ NOT NULL,
    revoked_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (session_id, user_id) REFERENCES sessions(id, user_id),
    CHECK (expires_at > created_at),
    CHECK (revoked_at IS NULL OR revoked_at >= created_at)
);
CREATE INDEX oauth_grants_session_idx ON oauth_grants(session_id, id);
CREATE INDEX oauth_grants_user_client_idx ON oauth_grants(user_id, client_id, created_at DESC, id DESC);
CREATE INDEX oauth_grants_client_idx ON oauth_grants(client_id, id);
CREATE INDEX oauth_grants_expiry_idx ON oauth_grants(expires_at, id);

CREATE TABLE authorization_transactions (
    id UUID PRIMARY KEY,
    client_id UUID NOT NULL REFERENCES oauth_clients(id),
    preauth_hash BYTEA CHECK (preauth_hash IS NULL OR octet_length(preauth_hash) = 32),
    session_id UUID REFERENCES sessions(id),
    redirect_uri TEXT NOT NULL CHECK (char_length(redirect_uri) BETWEEN 1 AND 2048),
    scopes TEXT[] NOT NULL CHECK (cardinality(scopes) > 0 AND scopes <@ ARRAY['openid', 'profile', 'email']::TEXT[] AND 'openid' = ANY(scopes)),
    state TEXT NOT NULL CHECK (char_length(state) BETWEEN 16 AND 512 AND octet_length(state) = char_length(state) AND state !~ '[[:cntrl:]]'),
    nonce TEXT NOT NULL CHECK (char_length(nonce) BETWEEN 16 AND 512 AND octet_length(nonce) = char_length(nonce) AND nonce !~ '[[:cntrl:]]'),
    code_challenge TEXT NOT NULL CHECK (code_challenge ~ '^[A-Za-z0-9_-]{43}$'),
    code_challenge_method TEXT NOT NULL DEFAULT 'S256' CHECK (code_challenge_method = 'S256'),
    prompt TEXT[] NOT NULL DEFAULT '{}' CHECK (prompt <@ ARRAY['login', 'consent', 'none']::TEXT[] AND (NOT ('none' = ANY(prompt)) OR cardinality(prompt) = 1)),
    max_age BIGINT CHECK (max_age IS NULL OR max_age >= 0),
    expires_at TIMESTAMPTZ NOT NULL,
    consumed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (num_nonnulls(preauth_hash, session_id) = 1),
    CHECK (expires_at > created_at AND expires_at <= created_at + INTERVAL '5 minutes'),
    CHECK (consumed_at IS NULL OR consumed_at >= created_at)
);
CREATE INDEX authorization_transactions_preauth_idx ON authorization_transactions(preauth_hash, expires_at) WHERE consumed_at IS NULL;
CREATE INDEX authorization_transactions_session_idx ON authorization_transactions(session_id, expires_at) WHERE consumed_at IS NULL;
CREATE INDEX authorization_transactions_expiry_idx ON authorization_transactions(expires_at, id);

CREATE TABLE authorization_codes (
    id UUID PRIMARY KEY,
    code_hash BYTEA NOT NULL UNIQUE CHECK (octet_length(code_hash) = 32),
    grant_id UUID NOT NULL REFERENCES oauth_grants(id),
    redirect_uri TEXT NOT NULL CHECK (char_length(redirect_uri) BETWEEN 1 AND 2048),
    code_challenge TEXT NOT NULL CHECK (code_challenge ~ '^[A-Za-z0-9_-]{43}$'),
    code_challenge_method TEXT NOT NULL DEFAULT 'S256' CHECK (code_challenge_method = 'S256'),
    nonce TEXT NOT NULL CHECK (char_length(nonce) BETWEEN 16 AND 512 AND octet_length(nonce) = char_length(nonce)),
    expires_at TIMESTAMPTZ NOT NULL,
    consumed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (expires_at > created_at AND expires_at <= created_at + INTERVAL '60 seconds'),
    CHECK (consumed_at IS NULL OR consumed_at >= created_at)
);
CREATE INDEX authorization_codes_grant_idx ON authorization_codes(grant_id, id);
CREATE INDEX authorization_codes_expiry_idx ON authorization_codes(expires_at, id);

CREATE TABLE oauth_tokens (
    id UUID PRIMARY KEY,
    token_hash BYTEA NOT NULL UNIQUE CHECK (octet_length(token_hash) = 32),
    kind TEXT NOT NULL CHECK (kind IN ('access', 'refresh')),
    grant_id UUID NOT NULL REFERENCES oauth_grants(id),
    family_id UUID NOT NULL,
    family_expires_at TIMESTAMPTZ NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    consumed_at TIMESTAMPTZ,
    revoked_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (family_expires_at > created_at),
    CHECK (expires_at > created_at AND expires_at <= family_expires_at),
    CHECK (kind <> 'access' OR (expires_at <= created_at + INTERVAL '5 minutes' AND consumed_at IS NULL)),
    CHECK (consumed_at IS NULL OR consumed_at >= created_at),
    CHECK (revoked_at IS NULL OR revoked_at >= created_at)
);
CREATE INDEX oauth_tokens_grant_idx ON oauth_tokens(grant_id, id);
CREATE INDEX oauth_tokens_family_idx ON oauth_tokens(family_id, kind, id);
CREATE INDEX oauth_tokens_expiry_idx ON oauth_tokens(expires_at, id);
CREATE INDEX oauth_tokens_refresh_retention_idx ON oauth_tokens(family_expires_at, id) WHERE kind = 'refresh';

CREATE TABLE user_consents (
    id UUID PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES users(id),
    client_id UUID NOT NULL REFERENCES oauth_clients(id),
    scopes TEXT[] NOT NULL CHECK (cardinality(scopes) > 0 AND scopes <@ ARRAY['openid', 'profile', 'email']::TEXT[]),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (user_id, client_id),
    CHECK (updated_at >= created_at)
);
CREATE INDEX user_consents_client_idx ON user_consents(client_id);

CREATE TABLE email_actions (
    id UUID PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES users(id),
    token_hash BYTEA NOT NULL UNIQUE CHECK (octet_length(token_hash) = 32),
    purpose TEXT NOT NULL CHECK (purpose IN ('verify', 'reset')),
    expires_at TIMESTAMPTZ NOT NULL,
    consumed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (expires_at > created_at AND expires_at <= created_at + CASE purpose WHEN 'verify' THEN INTERVAL '30 minutes' ELSE INTERVAL '15 minutes' END),
    CHECK (consumed_at IS NULL OR consumed_at >= created_at)
);
CREATE INDEX email_actions_user_purpose_idx ON email_actions(user_id, purpose, created_at DESC, id DESC);
CREATE INDEX email_actions_expiry_idx ON email_actions(expires_at, id);

CREATE TABLE authentication_challenges (
    id UUID PRIMARY KEY,
    user_id UUID REFERENCES users(id),
    preauth_hash BYTEA CHECK (preauth_hash IS NULL OR octet_length(preauth_hash) = 32),
    session_id UUID,
    purpose TEXT NOT NULL CHECK (purpose IN ('login', 'reauthentication', 'totp_enrollment', 'passkey_registration', 'passkey_login', 'passkey_reauthentication')),
    state_encrypted JSONB,
    state_data JSONB,
    attempts INTEGER NOT NULL DEFAULT 0 CHECK (attempts BETWEEN 0 AND 5),
    expires_at TIMESTAMPTZ NOT NULL,
    consumed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (session_id, user_id) REFERENCES sessions(id, user_id),
    CHECK (num_nonnulls(preauth_hash, session_id) = 1),
    CHECK (session_id IS NULL OR user_id IS NOT NULL),
    CHECK ((purpose IN ('login', 'passkey_login') AND preauth_hash IS NOT NULL) OR (purpose NOT IN ('login', 'passkey_login') AND session_id IS NOT NULL)),
    CHECK (user_id IS NOT NULL OR purpose = 'passkey_login'),
    CHECK (state_data IS NULL OR jsonb_typeof(state_data) = 'object'),
    CHECK (state_encrypted IS NULL OR (jsonb_typeof(state_encrypted) = 'object' AND state_encrypted ?& ARRAY['kid','nonce','ciphertext'] AND jsonb_typeof(state_encrypted->'kid') = 'string' AND jsonb_typeof(state_encrypted->'nonce') = 'string' AND jsonb_typeof(state_encrypted->'ciphertext') = 'string')),
    CHECK (expires_at > created_at AND expires_at <= created_at + INTERVAL '5 minutes'),
    CHECK (consumed_at IS NULL OR consumed_at >= created_at)
);
CREATE INDEX authentication_challenges_user_idx ON authentication_challenges(user_id, expires_at);
CREATE INDEX authentication_challenges_session_idx ON authentication_challenges(session_id, expires_at);
CREATE INDEX authentication_challenges_expiry_idx ON authentication_challenges(expires_at, id);

CREATE TABLE totp_factors (
    id UUID PRIMARY KEY,
    user_id UUID NOT NULL UNIQUE REFERENCES users(id),
    encrypted_seed BYTEA NOT NULL CHECK (octet_length(encrypted_seed) >= 16),
    encryption_kid TEXT NOT NULL CHECK (char_length(encryption_kid) BETWEEN 1 AND 128),
    encryption_nonce BYTEA NOT NULL CHECK (octet_length(encryption_nonce) = 12),
    confirmed BOOLEAN NOT NULL DEFAULT FALSE,
    last_step BIGINT NOT NULL DEFAULT -1 CHECK (last_step >= -1),
    enrollment_expires_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (confirmed OR enrollment_expires_at IS NOT NULL),
    CHECK (enrollment_expires_at IS NULL OR enrollment_expires_at > created_at)
);

CREATE TABLE recovery_codes (
    id UUID PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES users(id),
    code_hash BYTEA NOT NULL CHECK (octet_length(code_hash) = 32),
    consumed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (user_id, code_hash),
    CHECK (consumed_at IS NULL OR consumed_at >= created_at)
);
CREATE INDEX recovery_codes_unused_user_idx ON recovery_codes(user_id, id) WHERE consumed_at IS NULL;

CREATE TABLE webauthn_credentials (
    id UUID PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES users(id),
    credential_id BYTEA NOT NULL UNIQUE CHECK (octet_length(credential_id) BETWEEN 1 AND 1024),
    credential_data JSONB NOT NULL CHECK (jsonb_typeof(credential_data) = 'object'),
    name TEXT NOT NULL CHECK (char_length(name) BETWEEN 1 AND 100),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (updated_at >= created_at)
);
CREATE INDEX webauthn_credentials_user_idx ON webauthn_credentials(user_id, created_at, id);

CREATE TABLE admin_memberships (
    id UUID PRIMARY KEY,
    user_id UUID NOT NULL UNIQUE REFERENCES users(id),
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE email_outbox (
    id UUID PRIMARY KEY,
    user_id UUID REFERENCES users(id),
    recipient TEXT NOT NULL CHECK (char_length(recipient) BETWEEN 3 AND 254 AND octet_length(recipient) = char_length(recipient) AND recipient !~ '[[:cntrl:][:space:]]'),
    template TEXT NOT NULL CHECK (template IN ('verify_email', 'reset_password', 'security_notification')),
    encrypted_params JSONB,
    state TEXT NOT NULL DEFAULT 'pending' CHECK (state IN ('pending', 'delivered', 'failed')),
    attempts INTEGER NOT NULL DEFAULT 0 CHECK (attempts >= 0),
    next_attempt_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    lease_id UUID,
    lease_until TIMESTAMPTZ,
    delivered_at TIMESTAMPTZ,
    failed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK ((lease_id IS NULL) = (lease_until IS NULL)),
    CHECK (encrypted_params IS NULL OR (jsonb_typeof(encrypted_params) = 'object' AND encrypted_params ?& ARRAY['kid','nonce','ciphertext'] AND jsonb_typeof(encrypted_params->'kid') = 'string' AND jsonb_typeof(encrypted_params->'nonce') = 'string' AND jsonb_typeof(encrypted_params->'ciphertext') = 'string')),
    CHECK ((state = 'pending' AND delivered_at IS NULL AND failed_at IS NULL AND encrypted_params IS NOT NULL) OR (state = 'delivered' AND delivered_at IS NOT NULL AND failed_at IS NULL AND encrypted_params IS NULL AND lease_id IS NULL) OR (state = 'failed' AND failed_at IS NOT NULL AND delivered_at IS NULL AND lease_id IS NULL)),
    CHECK (delivered_at IS NULL OR delivered_at >= created_at),
    CHECK (failed_at IS NULL OR failed_at >= created_at)
);
CREATE INDEX email_outbox_claim_idx ON email_outbox(next_attempt_at, created_at, id) WHERE state = 'pending';
CREATE INDEX email_outbox_lease_idx ON email_outbox(lease_until, id) WHERE state = 'pending' AND lease_until IS NOT NULL;
CREATE INDEX email_outbox_delivered_retention_idx ON email_outbox(delivered_at, id) WHERE state = 'delivered';
CREATE INDEX email_outbox_failed_retention_idx ON email_outbox(failed_at, id) WHERE state = 'failed';
CREATE INDEX email_outbox_user_idx ON email_outbox(user_id, created_at, id);

CREATE TABLE audit_events (
    id UUID PRIMARY KEY,
    event TEXT NOT NULL CHECK (char_length(event) BETWEEN 1 AND 100 AND event ~ '^[a-z][a-z0-9_.]+$'),
    actor_id UUID REFERENCES users(id),
    target_type TEXT NOT NULL CHECK (char_length(target_type) BETWEEN 1 AND 64),
    target_id UUID,
    result TEXT NOT NULL CHECK (result IN ('success', 'denied', 'failure')),
    reason_code TEXT CHECK (reason_code IS NULL OR (char_length(reason_code) BETWEEN 1 AND 100 AND reason_code ~ '^[A-Z][A-Z0-9_]+$')),
    request_id UUID NOT NULL,
    source TEXT NOT NULL DEFAULT '' CHECK (char_length(source) <= 256),
    occurred_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX audit_events_time_id_idx ON audit_events(occurred_at DESC, id DESC);
CREATE INDEX audit_events_actor_time_idx ON audit_events(actor_id, occurred_at DESC, id DESC);
CREATE INDEX audit_events_target_time_idx ON audit_events(target_type, target_id, occurred_at DESC, id DESC);
