import * as Dialog from '@radix-ui/react-dialog';
import { useRef, useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { adminApi } from '../../lib/admin-api';
import type { AdminClient, ClientInput } from '../../lib/admin-api';
import { ApiError } from '../../lib/api';
import { asApiError, useRetryAfter } from '../../lib/auth-feedback';
import { Button } from '../../components/Button';
import { Input } from '../../components/Input';
import { Status } from '../../components/Status';
import { CursorPagination } from '../../components/CursorPagination';
import { Empty } from '../../components/Empty';
import { ReauthenticationDialog } from '../../components/ReauthenticationDialog';
import { AdminAction, AdminFailure, AdminPanel, AdminTable } from './AdminShared';
import { PageTitle } from '../PageTitle';

type Secret = { client_id: string; client_secret: string };
const blank: ClientInput = { name: '', allowed_scopes: ['openid'], redirect_uris: [], post_logout_redirect_uris: [] };
export default function ClientsPage() {
  const [cursor, setCursor] = useState<string | undefined>(); const [history, setHistory] = useState<(string | undefined)[]>([]); const [editing, setEditing] = useState<AdminClient | null>(null); const [draft, setDraft] = useState<ClientInput>(blank); const [redirects, setRedirects] = useState(''); const [logout, setLogout] = useState(''); const [secret, setSecret] = useState<Secret | null>(null); const [busy, setBusy] = useState(false); const [failure, setFailure] = useState<ApiError | null>(null); const [reauth, setReauth] = useState(false); const inFlight = useRef(false); const retry = useRetryAfter(); const closeSecret = useRef<HTMLButtonElement>(null); const pendingSecret = useRef<Secret | null>(null);
  const query = useQuery({ queryKey: ['admin', 'clients', cursor], queryFn: ({ signal }) => adminApi.clients(cursor, signal), retry: false });
  const [identityConfirmed, setIdentityConfirmed] = useState(false);
  const createTrigger = useRef<HTMLButtonElement>(null); const secretOpener = useRef<HTMLElement | null>(null);
  function edit(client: AdminClient) { setEditing(client); setDraft({ name: client.name, allowed_scopes: client.allowed_scopes, redirect_uris: client.redirect_uris, post_logout_redirect_uris: client.post_logout_redirect_uris }); setRedirects(client.redirect_uris.join('\n')); setLogout(client.post_logout_redirect_uris.join('\n')); setFailure(null); }
  function clearEditor() { setEditing(null); setDraft(blank); setRedirects(''); setLogout(''); }
  async function save() {
    if (inFlight.current || retry.remaining > 0) return; const urls = redirects.split('\n').map((value) => value.trim()).filter(Boolean); const logoutUrls = logout.split('\n').map((value) => value.trim()).filter(Boolean);
    if (draft.name.trim() === '' || draft.name.length > 100 || urls.length === 0 || urls.length > 20 || logoutUrls.length > 20 || [...urls, ...logoutUrls].some((value) => { try { const uri = new URL(value); return !['https:', 'http:'].includes(uri.protocol) || value.includes('*') || uri.hash !== '' || uri.username !== ''; } catch { return true; } })) { setFailure(new ApiError(422, 'INPUT_INVALID', '请填写应用名称和完整、精确的回调地址。')); return; }
    if (!identityConfirmed) { setReauth(true); return; }
    const body = { ...draft, redirect_uris: urls, post_logout_redirect_uris: logoutUrls }; inFlight.current = true; setBusy(true); setFailure(null);
    try { if (editing) await adminApi.updateClient(editing.id, body); else { const created = await adminApi.createClient(body); secretOpener.current = createTrigger.current; setSecret({ client_id: created.client.client_id, client_secret: created.client_secret }); } clearEditor(); setIdentityConfirmed(false); await query.refetch(); } catch (error) { const detail = asApiError(error); setFailure(detail); retry.start(detail); if (detail.next?.status === 'reauth_required') { setIdentityConfirmed(false); setReauth(true); } } finally { setBusy(false); inFlight.current = false; }
  }
  return <><PageTitle title="应用客户端" /><h1>应用客户端</h1><p className="muted">管理服务端接入应用、精确回调和允许的身份范围。</p><AdminPanel><h2>{editing ? `编辑 ${editing.name}` : '创建应用客户端'}</h2><form onSubmit={(event) => { event.preventDefault(); void save(); }}><Input label="应用名称" value={draft.name} maxLength={100} onChange={(event) => { setDraft({ ...draft, name: event.target.value }); }} /><fieldset><legend>允许的身份范围</legend>{(['openid', 'profile', 'email'] as const).map((scope) => <label key={scope}><input type="checkbox" checked={draft.allowed_scopes.includes(scope)} disabled={scope === 'openid'} onChange={(event) => { setDraft({ ...draft, allowed_scopes: event.target.checked ? [...draft.allowed_scopes, scope] : draft.allowed_scopes.filter((item) => item !== scope) }); }} />{scope}</label>)}</fieldset><label>登录回调地址（每行一个）<textarea value={redirects} onChange={(event) => { setRedirects(event.target.value); }} rows={3} /></label><label>退出回调地址（每行一个）<textarea value={logout} onChange={(event) => { setLogout(event.target.value); }} rows={3} /></label><p className="muted">不接受通配符或地址前缀。创建成功后，客户端秘密只显示一次。</p><div className="actions"><Button ref={createTrigger} type="submit" variant="primary" loading={busy} disabled={retry.remaining > 0} loadingLabel="正在保存…">{retry.remaining > 0 ? `${String(retry.remaining)}秒后可重试` : editing ? '保存客户端' : '创建客户端'}</Button>{editing && <Button disabled={busy} onClick={clearEditor}>取消编辑</Button>}</div></form>{failure && <Status kind={failure.status === 429 ? 'limited' : failure.status === 503 || failure.status === 0 ? 'unavailable' : 'error'} title="客户端未保存" description={failure.message} requestId={failure.requestId} />}</AdminPanel>
    <AdminPanel>{query.isPending ? <Status kind="loading" title="正在读取客户端…" /> : query.isError ? <AdminFailure error={query.error} retry={() => { void query.refetch(); }} /> : query.data.items.length === 0 ? <Empty title="尚未创建客户端" description="创建后可在这里管理接入应用。" /> : <AdminTable caption="客户端列表" columns={[{ key: 'name', header: '应用' }, { key: 'status', header: '状态' }, { key: 'scope', header: '身份范围' }, { key: 'actions', header: '操作' }]} rows={query.data.items.map((client) => ({ id: client.id, cells: { name: <><p>{client.name}</p><code>{client.client_id}</code></>, status: client.enabled ? '可用' : '已停用', scope: client.allowed_scopes.join('、'), actions: <div className="actions"><Button onClick={() => { edit(client); }}>编辑客户端</Button><AdminAction label={client.enabled ? '停用客户端' : '启用客户端'} title="更改客户端状态？" description="停用后该应用的凭证检查将无效；操作不会删除客户端。" danger={client.enabled} action={() => adminApi.updateClient(client.id, { enabled: !client.enabled })} onComplete={async () => { await query.refetch(); }} /><AdminAction label="轮换客户端秘密" title="轮换客户端秘密？" description="旧秘密立即失效，新秘密只显示一次。请同步更新该应用的服务端配置。" danger action={async () => { const rotated = await adminApi.rotateSecret(client.id); pendingSecret.current = { client_id: rotated.client_id, client_secret: rotated.client_secret }; }} onComplete={async (opener) => { secretOpener.current = opener ?? createTrigger.current; setSecret(pendingSecret.current); pendingSecret.current = null; await query.refetch(); }} /></div> } }))} />}<CursorPagination hasPrevious={history.length > 0} hasNext={query.data?.next_cursor != null} loading={query.isFetching} onPrevious={() => { setCursor(history.at(-1)); setHistory(history.slice(0, -1)); }} onNext={() => { if (query.data?.next_cursor) { setHistory([...history, cursor]); setCursor(query.data.next_cursor); } }} /></AdminPanel>
    <Dialog.Root open={secret !== null} onOpenChange={(open) => { if (!open) setSecret(null); }}><Dialog.Portal><Dialog.Overlay className="dialog-overlay" /><Dialog.Content className="dialog-content" onOpenAutoFocus={(event) => { event.preventDefault(); closeSecret.current?.focus(); }} onCloseAutoFocus={(event) => { event.preventDefault(); const target = secretOpener.current; if (target?.isConnected) target.focus(); else createTrigger.current?.focus(); secretOpener.current = null; }}><Dialog.Title>保存客户端秘密</Dialog.Title><Dialog.Description>秘密只在本次结果中显示。关闭后无法再次读取，请保存到该应用的服务端秘密管理中。</Dialog.Description><p>客户端：{secret?.client_id}</p><p className="setup-secret">{secret?.client_secret}</p><Button ref={closeSecret} onClick={() => { setSecret(null); }}>已保存，关闭秘密</Button></Dialog.Content></Dialog.Portal></Dialog.Root>
    <ReauthenticationDialog open={reauth} onOpenChange={setReauth} requiredStrength="strong" {...(failure?.next === undefined ? {} : { methods: failure.next.methods })} onConfirmed={() => { setFailure(null); setIdentityConfirmed(true); }} />
  </>;
}
